/**
 * changqingnvshu - Nushu Data & Core Utilities
 * 汉字 ↔ 女书 转换引擎
 * 数据来源：数据/nushu.txt
 */
// ===== Nushu Data (loaded from 数据/nushu.json) =====
let NUSHU_DATA = [
  {hanzi:"一",nushu:["𛆼","𛅰"]},
  {hanzi:"丁",nushu:["𛉼"]},
  {hanzi:"七",nushu:["𛅲"]},
  {hanzi:"万",nushu:["𛈄","𛆨"]},
  {hanzi:"丈",nushu:["𛊪","𛈼"]},
  {hanzi:"三",nushu:["𛆊"]},
  {hanzi:"上",nushu:["𛆈"]},
  {hanzi:"下",nushu:["𛅽"]},
  {hanzi:"不",nushu:["𛆳"]},
  {hanzi:"与",nushu:["𛉟","𛈶","𛇄","𛆱"]},
  {hanzi:"丑",nushu:["𛆞"]},
  {hanzi:"专",nushu:["𛈌"]},
  {hanzi:"且",nushu:["𛊴","𛇠"]},
  {hanzi:"世",nushu:["𛆓"]},
  {hanzi:"丘",nushu:["𛆝"]},
  {hanzi:"丙",nushu:["𛇛"]},
  {hanzi:"业",nushu:["𛈥"]},
  {hanzi:"东",nushu:["𛊚"]},
  {hanzi:"丝",nushu:["𛊸"]},
  {hanzi:"丞",nushu:["𛋙"]},
  {hanzi:"两",nushu:["𛆇","𛅱"]},
  {hanzi:"严",nushu:["𛋍","𛋋"]},
  {hanzi:"丧",nushu:["𛈊","𛆢"]},
  {hanzi:"个",nushu:["𛉦","𛇢","𛆯","𛆅"]},
  {hanzi:"丫",nushu:["𛆴","𛅹"]},
  {hanzi:"中",nushu:["𛈌"]},
  {hanzi:"丰",nushu:["𛆠"]},
  {hanzi:"串",nushu:["𛆟"]},
  {hanzi:"丹",nushu:["𛈁","𛆍"]},
  {hanzi:"为",nushu:["𛊄","𛆨"]},
  {hanzi:"主",nushu:["𛋱","𛋒","𛆺","𛆗"]},
  {hanzi:"举",nushu:["𛆺","𛆗"]},
  {hanzi:"久",nushu:["𛆆"]},
  {hanzi:"义",nushu:["𛅺"]},
  {hanzi:"之",nushu:["𛈤","𛆷"]},
  {hanzi:"乌",nushu:["𛉍","𛇯"]},
  {hanzi:"乐",nushu:["𛋧"]},
  {hanzi:"乔",nushu:["𛊻"]},
  {hanzi:"乖",nushu:["𛉌","𛇧"]},
  {hanzi:"乘",nushu:["𛋙"]},
  {hanzi:"九",nushu:["𛆆"]},
  {hanzi:"也",nushu:["𛇁"]},
  {hanzi:"习",nushu:["𛆓"]},
  {hanzi:"乡",nushu:["𛉶"]},
  {hanzi:"书",nushu:["𛈬"]},
  {hanzi:"买",nushu:["𛊊","𛉟"]},
  {hanzi:"乱",nushu:["𛋈"]},
  {hanzi:"乾",nushu:["𛉉","𛈆"]},
  {hanzi:"了",nushu:["𛆒","𛅹"]},
  {hanzi:"争",nushu:["𛋩"]},
  {hanzi:"事",nushu:["𛆹","𛅵"]},
  {hanzi:"二",nushu:["𛆇","𛅱"]},
  {hanzi:"于",nushu:["𛆱"]},
  {hanzi:"亏",nushu:["𛆩"]},
  {hanzi:"云",nushu:["𛉍"]},
  {hanzi:"互",nushu:["𛆖"]},
  {hanzi:"五",nushu:["𛈕"]},
  {hanzi:"井",nushu:["𛇆","𛆦"]},
  {hanzi:"些",nushu:["𛇠"]},
  {hanzi:"亡",nushu:["𛋅","𛉯","𛆡"]},
  {hanzi:"交",nushu:["𛆝"]},
  {hanzi:"亦",nushu:["𛇁","𛆯"]},
  {hanzi:"产",nushu:["𛊜"]},
  {hanzi:"亩",nushu:["𛇀"]},
  {hanzi:"享",nushu:["𛉷"]},
  {hanzi:"京",nushu:["𛋭","𛇆"]},
  {hanzi:"亭",nushu:["𛊭"]},
  {hanzi:"亮",nushu:["𛉴","𛇖"]},
  {hanzi:"亲",nushu:["𛋴"]},
  {hanzi:"人",nushu:["𛅳"]},
  {hanzi:"仇",nushu:["𛉬"]},
  {hanzi:"今",nushu:["𛆭"]},
  {hanzi:"介",nushu:["𛇧","𛆅","𛆄"]},
  {hanzi:"仍",nushu:["𛋍"]},
  {hanzi:"从",nushu:["𛋳","𛈽"]},
  {hanzi:"仓",nushu:["𛉱"]},
  {hanzi:"仔",nushu:["𛆑"]},
  {hanzi:"仕",nushu:["𛆹"]},
  {hanzi:"他",nushu:["𛆶"]},
  {hanzi:"仗",nushu:["𛋬","𛊪"]},
  {hanzi:"付",nushu:["𛈩","𛆖"]},
  {hanzi:"仙",nushu:["𛇚"]},
  {hanzi:"代",nushu:["𛅻"]},
  {hanzi:"令",nushu:["𛉼"]},
  {hanzi:"以",nushu:["𛋤","𛆼","𛆱","𛅺"]},
  {hanzi:"仪",nushu:["𛅺"]},
  {hanzi:"件",nushu:["𛇝"]},
  {hanzi:"价",nushu:["𛉌","𛉋","𛈅","𛇧"]},
  {hanzi:"任",nushu:["𛊉","𛆲","𛆱"]},
  {hanzi:"份",nushu:["𛋆","𛆙"]},
  {hanzi:"伏",nushu:["𛈩","𛆖"]},
  {hanzi:"休",nushu:["𛈀"]},
  {hanzi:"众",nushu:["𛊪"]},
  {hanzi:"会",nushu:["𛋶","𛆴"]},
  {hanzi:"伞",nushu:["𛊜","𛇠"]},
  {hanzi:"传",nushu:["𛈆"]},
  {hanzi:"伤",nushu:["𛉶"]},
  {hanzi:"伪",nushu:["𛊄"]},
  {hanzi:"估",nushu:["𛊿"]},
  {hanzi:"伴",nushu:["𛈺"]},
  {hanzi:"伸",nushu:["𛈛"]},
  {hanzi:"似",nushu:["𛊝"]},
  {hanzi:"佃",nushu:["𛋊"]},
  {hanzi:"但",nushu:["𛉻"]},
  {hanzi:"位",nushu:["𛈕","𛆨"]},
  {hanzi:"低",nushu:["𛊚","𛆒","𛅾"]},
  {hanzi:"住",nushu:["𛇭"]},
  {hanzi:"佑",nushu:["𛇁"]},
  {hanzi:"体",nushu:["𛋒"]},
  {hanzi:"何",nushu:["𛇮"]},
  {hanzi:"余",nushu:["𛇄"]},
  {hanzi:"佛",nushu:["𛋶"]},
  {hanzi:"作",nushu:["𛊅","𛈱","𛇎","𛇍"]},
  {hanzi:"你",nushu:["𛊂","𛈻"]},
  {hanzi:"佩",nushu:["𛈭"]},
  {hanzi:"佰",nushu:["𛇫"]},
  {hanzi:"佳",nushu:["𛉊"]},
  {hanzi:"使",nushu:["𛇴"]},
  {hanzi:"侄",nushu:["𛇴"]},
  {hanzi:"侍",nushu:["𛆹","𛅵"]},
  {hanzi:"供",nushu:["𛈌"]},
  {hanzi:"依",nushu:["𛋕","𛊺","𛆱"]},
  {hanzi:"侬",nushu:["𛈏","𛆥"]},
  {hanzi:"侵",nushu:["𛋴"]},
  {hanzi:"便",nushu:["𛇪","𛇙"]},
  {hanzi:"俊",nushu:["𛊶"]},
  {hanzi:"保",nushu:["𛉎"]},
  {hanzi:"信",nushu:["𛉡"]},
  {hanzi:"俫",nushu:["𛈞"]},
  {hanzi:"修",nushu:["𛉪"]},
  {hanzi:"俱",nushu:["𛋔"]},
  {hanzi:"倒",nushu:["𛇼"]},
  {hanzi:"候",nushu:["𛋄","𛆚"]},
  {hanzi:"倚",nushu:["𛋕"]},
  {hanzi:"借",nushu:["𛋮","𛋓","𛋏","𛊖","𛊈"]},
  {hanzi:"债",nushu:["𛇥"]},
  {hanzi:"值",nushu:["𛋔"]},
  {hanzi:"倾",nushu:["𛊯"]},
  {hanzi:"假",nushu:["𛉋"]},
  {hanzi:"偏",nushu:["𛇙"]},
  {hanzi:"做",nushu:["𛊅","𛇎"]},
  {hanzi:"停",nushu:["𛊭","𛊍"]},
  {hanzi:"偷",nushu:["𛋃"]},
  {hanzi:"偿",nushu:["𛈾"]},
  {hanzi:"傅",nushu:["𛆔"]},
  {hanzi:"傺",nushu:["𛅲"]},
  {hanzi:"像",nushu:["𛊪","𛈼"]},
  {hanzi:"僚",nushu:["𛇇"]},
  {hanzi:"僧",nushu:["𛋳"]},
  {hanzi:"儒",nushu:["𛆱"]},
  {hanzi:"儿",nushu:["𛇈"]},
  {hanzi:"元",nushu:["𛆧"]},
  {hanzi:"兄",nushu:["𛉂"]},
  {hanzi:"兆",nushu:["𛉓"]},
  {hanzi:"先",nushu:["𛇚"]},
  {hanzi:"光",nushu:["𛇕"]},
  {hanzi:"免",nushu:["𛋉"]},
  {hanzi:"兑",nushu:["𛆬"]},
  {hanzi:"党",nushu:["𛋈","𛊥"]},
  {hanzi:"兜",nushu:["𛋧","𛋃"]},
  {hanzi:"兢",nushu:["𛋭"]},
  {hanzi:"入",nushu:["𛇈","𛇄","𛅱"]},
  {hanzi:"全",nushu:["𛈆"]},
  {hanzi:"八",nushu:["𛅴"]},
  {hanzi:"公",nushu:["𛈌","𛇕","𛆃"]},
  {hanzi:"六",nushu:["𛆜"]},
  {hanzi:"共",nushu:["𛉨","𛈌"]},
  {hanzi:"关",nushu:["𛈘","𛇕"]},
  {hanzi:"兴",nushu:["𛋐","𛈛"]},
  {hanzi:"兵",nushu:["𛈐","𛆦"]},
  {hanzi:"其",nushu:["𛊻","𛆦"]},
  {hanzi:"具",nushu:["𛉙"]},
  {hanzi:"典",nushu:["𛉸"]},
  {hanzi:"兹",nushu:["𛈤"]},
  {hanzi:"养",nushu:["𛈍"]},
  {hanzi:"兼",nushu:["𛉿"]},
  {hanzi:"内",nushu:["𛈏","𛆫","𛅺"]},
  {hanzi:"冈",nushu:["𛇕"]},
  {hanzi:"再",nushu:["𛇥"]},
  {hanzi:"冒",nushu:["𛉣"]},
  {hanzi:"写",nushu:["𛇠"]},
  {hanzi:"军",nushu:["𛊶","𛊵"]},
  {hanzi:"冠",nushu:["𛇕"]},
  {hanzi:"冤",nushu:["𛋟"]},
  {hanzi:"冬",nushu:["𛊚"]},
  {hanzi:"冰",nushu:["𛋆"]},
  {hanzi:"决",nushu:["𛊐"]},
  {hanzi:"冷",nushu:["𛉼"]},
  {hanzi:"冻",nushu:["𛆒"]},
  {hanzi:"净",nushu:["𛉽"]},
  {hanzi:"凄",nushu:["𛋴","𛈨"]},
  {hanzi:"凉",nushu:["𛉴"]},
  {hanzi:"减",nushu:["𛊜","𛇕"]},
  {hanzi:"凑",nushu:["𛉵"]},
  {hanzi:"几",nushu:["𛆺"]},
  {hanzi:"凡",nushu:["𛈒"]},
  {hanzi:"凤",nushu:["𛋹","𛆠"]},
  {hanzi:"凭",nushu:["𛋆"]},
  {hanzi:"凳",nushu:["𛇽","𛇼","𛆬","𛆒"]},
  {hanzi:"出",nushu:["𛈚"]},
  {hanzi:"击",nushu:["𛊐"]},
  {hanzi:"刀",nushu:["𛆒"]},
  {hanzi:"刁",nushu:["𛅾"]},
  {hanzi:"分",nushu:["𛋆","𛆙"]},
  {hanzi:"切",nushu:["𛈦"]},
  {hanzi:"刑",nushu:["𛊁"]},
  {hanzi:"划",nushu:["𛆵"]},
  {hanzi:"刘",nushu:["𛇋"]},
  {hanzi:"则",nushu:["𛈤"]},
  {hanzi:"刚",nushu:["𛈌","𛇕"]},
  {hanzi:"初",nushu:["𛊾"]},
  {hanzi:"判",nushu:["𛋪","𛈺"]},
  {hanzi:"利",nushu:["𛇟","𛆍"]},
  {hanzi:"别",nushu:["𛊎"]},
  {hanzi:"刮",nushu:["𛆐"]},
  {hanzi:"到",nushu:["𛇽","𛇼","𛆛"]},
  {hanzi:"制",nushu:["𛊝","𛉓","𛈤"]},
  {hanzi:"刹",nushu:["𛇦"]},
  {hanzi:"刺",nushu:["𛇠"]},
  {hanzi:"刻",nushu:["𛊙"]},
  {hanzi:"剃",nushu:["𛉕"]},
  {hanzi:"削",nushu:["𛅿"]},
  {hanzi:"前",nushu:["𛋋"]},
  {hanzi:"剥",nushu:["𛈲"]},
  {hanzi:"剩",nushu:["𛋐","𛈛"]},
  {hanzi:"割",nushu:["𛇵"]},
  {hanzi:"劝",nushu:["𛆟"]},
  {hanzi:"功",nushu:["𛇕","𛆃"]},
  {hanzi:"加",nushu:["𛉊"]},
  {hanzi:"务",nushu:["𛈩"]},
  {hanzi:"动",nushu:["𛆒"]},
  {hanzi:"助",nushu:["𛊾","𛉊","𛇭"]},
  {hanzi:"劫",nushu:["𛊐"]},
  {hanzi:"劳",nushu:["𛈰","𛇇"]},
  {hanzi:"势",nushu:["𛆓"]},
  {hanzi:"勘",nushu:["𛆣"]},
  {hanzi:"勤",nushu:["𛊝"]},
  {hanzi:"勾",nushu:["𛋂"]},
  {hanzi:"匀",nushu:["𛉍","𛇁"]},
  {hanzi:"包",nushu:["𛈲"]},
  {hanzi:"化",nushu:["𛅽"]},
  {hanzi:"北",nushu:["𛉜","𛇫"]},
  {hanzi:"匙",nushu:["𛆸"]},
  {hanzi:"匠",nushu:["𛈼"]},
  {hanzi:"匣",nushu:["𛊕"]},
  {hanzi:"匹",nushu:["𛉆"]},
  {hanzi:"区",nushu:["𛇂"]},
  {hanzi:"医",nushu:["𛆱"]},
  {hanzi:"十",nushu:["𛆹","𛅵"]},
  {hanzi:"千",nushu:["𛆉"]},
  {hanzi:"升",nushu:["𛈛"]},
  {hanzi:"半",nushu:["𛈺"]},
  {hanzi:"华",nushu:["𛇳"]},
  {hanzi:"单",nushu:["𛈁","𛆍"]},
  {hanzi:"卖",nushu:["𛋯"]},
  {hanzi:"南",nushu:["𛉺"]},
  {hanzi:"博",nushu:["𛋷","𛉖"]},
  {hanzi:"卜",nushu:["𛇲"]},
  {hanzi:"占",nushu:["𛉿","𛉓","𛇝"]},
  {hanzi:"卢",nushu:["𛋗"]},
  {hanzi:"卦",nushu:["𛉌"]},
  {hanzi:"卫",nushu:["𛆨"]},
  {hanzi:"卯",nushu:["𛈳"]},
  {hanzi:"却",nushu:["𛅼"]},
  {hanzi:"卷",nushu:["𛉉","𛉅","𛇆"]},
  {hanzi:"卿",nushu:["𛊯"]},
  {hanzi:"厅",nushu:["𛊭"]},
  {hanzi:"厉",nushu:["𛇟"]},
  {hanzi:"压",nushu:["𛆵"]},
  {hanzi:"厘",nushu:["𛊎"]},
  {hanzi:"原",nushu:["𛆧"]},
  {hanzi:"厢",nushu:["𛉵"]},
  {hanzi:"厨",nushu:["𛇭"]},
  {hanzi:"去",nushu:["𛇂"]},
  {hanzi:"县",nushu:["𛋟"]},
  {hanzi:"参",nushu:["𛉾"]},
  {hanzi:"又",nushu:["𛇁"]},
  {hanzi:"及",nushu:["𛋔","𛉓"]},
  {hanzi:"友",nushu:["𛈶"]},
  {hanzi:"双",nushu:["𛈊"]},
  {hanzi:"反",nushu:["𛇑","𛆌"]},
  {hanzi:"发",nushu:["𛆐"]},
  {hanzi:"叔",nushu:["𛊡","𛅿"]},
  {hanzi:"取",nushu:["𛉛","𛇂"]},
  {hanzi:"受",nushu:["𛉬"]},
  {hanzi:"变",nushu:["𛇲","𛇪","𛆦"]},
  {hanzi:"口",nushu:["𛇉","𛆚"]},
  {hanzi:"古",nushu:["𛇰"]},
  {hanzi:"句",nushu:["𛆘"]},
  {hanzi:"另",nushu:["𛉼"]},
  {hanzi:"叩",nushu:["𛆣"]},
  {hanzi:"只",nushu:["𛈤","𛆑"]},
  {hanzi:"叫",nushu:["𛉓"]},
  {hanzi:"可",nushu:["𛆄"]},
  {hanzi:"台",nushu:["𛅻"]},
  {hanzi:"史",nushu:["𛆹"]},
  {hanzi:"右",nushu:["𛇁"]},
  {hanzi:"叶",nushu:["𛆼","𛆱"]},
  {hanzi:"号",nushu:["𛉥"]},
  {hanzi:"司",nushu:["𛊸"]},
  {hanzi:"吃",nushu:["𛋡","𛊉","𛆲","𛆱"]},
  {hanzi:"各",nushu:["𛉦"]},
  {hanzi:"合",nushu:["𛈩"]},
  {hanzi:"吉",nushu:["𛊐"]},
  {hanzi:"吊",nushu:["𛅹"]},
  {hanzi:"同",nushu:["𛊤"]},
  {hanzi:"名",nushu:["𛇾"]},
  {hanzi:"后",nushu:["𛇌"]},
  {hanzi:"向",nushu:["𛆈"]},
  {hanzi:"吓",nushu:["𛅽"]},
  {hanzi:"君",nushu:["𛊵"]},
  {hanzi:"吞",nushu:["𛇸"]},
  {hanzi:"吟",nushu:["𛆰"]},
  {hanzi:"吧",nushu:["𛇪"]},
  {hanzi:"含",nushu:["𛊨"]},
  {hanzi:"听",nushu:["𛇜"]},
  {hanzi:"启",nushu:["𛉛"]},
  {hanzi:"吴",nushu:["𛊢"]},
  {hanzi:"吵",nushu:["𛉤","𛈂"]},
  {hanzi:"吸",nushu:["𛊐"]},
  {hanzi:"吹",nushu:["𛆪"]},
  {hanzi:"呈",nushu:["𛈆"]},
  {hanzi:"告",nushu:["𛉘","𛇧","𛆅"]},
  {hanzi:"员",nushu:["𛆧"]},
  {hanzi:"周",nushu:["𛆝"]},
  {hanzi:"味",nushu:["𛆨"]},
  {hanzi:"命",nushu:["𛈑"]},
  {hanzi:"和",nushu:["𛇯","𛇮"]},
  {hanzi:"咐",nushu:["𛆖"]},
  {hanzi:"咒",nushu:["𛆝"]},
  {hanzi:"咬",nushu:["𛊠"]},
  {hanzi:"咸",nushu:["𛊨"]},
  {hanzi:"咽",nushu:["𛊂"]},
  {hanzi:"品",nushu:["𛉞"]},
  {hanzi:"响",nushu:["𛊩","𛉷"]},
  {hanzi:"哑",nushu:["𛉏"]},
  {hanzi:"哥",nushu:["𛋰","𛋂"]},
  {hanzi:"哪",nushu:["𛉈","𛈏","𛇾"]},
  {hanzi:"哭",nushu:["𛇱"]},
  {hanzi:"唐",nushu:["𛊤"]},
  {hanzi:"唤",nushu:["𛊧"]},
  {hanzi:"唯",nushu:["𛊄"]},
  {hanzi:"唱",nushu:["𛋬"]},
  {hanzi:"啄",nushu:["𛈺"]},
  {hanzi:"商",nushu:["𛉶"]},
  {hanzi:"啼",nushu:["𛊹"]},
  {hanzi:"善",nushu:["𛋌"]},
  {hanzi:"喊",nushu:["𛋄","𛊕","𛈹"]},
  {hanzi:"喜",nushu:["𛆻"]},
  {hanzi:"喝",nushu:["𛉦","𛈩"]},
  {hanzi:"喷",nushu:["𛅶"]},
  {hanzi:"喻",nushu:["𛆱"]},
  {hanzi:"嗯",nushu:["𛊃"]},
  {hanzi:"嘉",nushu:["𛈅"]},
  {hanzi:"嘱",nushu:["𛅼"]},
  {hanzi:"嘴",nushu:["𛆘"]},
  {hanzi:"四",nushu:["𛈗"]},
  {hanzi:"回",nushu:["𛇳"]},
  {hanzi:"因",nushu:["𛆱"]},
  {hanzi:"团",nushu:["𛊤"]},
  {hanzi:"园",nushu:["𛆧"]},
  {hanzi:"困",nushu:["𛋫"]},
  {hanzi:"围",nushu:["𛊄"]},
  {hanzi:"固",nushu:["𛇰"]},
  {hanzi:"国",nushu:["𛈅"]},
  {hanzi:"图",nushu:["𛋥"]},
  {hanzi:"圆",nushu:["𛆧"]},
  {hanzi:"土",nushu:["𛊔","𛆀"]},
  {hanzi:"圣",nushu:["𛈓"]},
  {hanzi:"在",nushu:["𛇥"]},
  {hanzi:"地",nushu:["𛋇","𛊤"]},
  {hanzi:"场",nushu:["𛊻"]},
  {hanzi:"均",nushu:["𛊵"]},
  {hanzi:"坏",nushu:["𛆌"]},
  {hanzi:"坐",nushu:["𛊅","𛇎"]},
  {hanzi:"坑",nushu:["𛆃"]},
  {hanzi:"块",nushu:["𛇨"]},
  {hanzi:"坚",nushu:["𛉿"]},
  {hanzi:"坟",nushu:["𛈮","𛆙"]},
  {hanzi:"坤",nushu:["𛉨"]},
  {hanzi:"坦",nushu:["𛉻"]},
  {hanzi:"垂",nushu:["𛉅"]},
  {hanzi:"垫",nushu:["𛋊","𛈎"]},
  {hanzi:"垮",nushu:["𛆩"]},
  {hanzi:"埋",nushu:["𛋑","𛊊"]},
  {hanzi:"城",nushu:["𛈒"]},
  {hanzi:"培",nushu:["𛇪"]},
  {hanzi:"基",nushu:["𛋔"]},
  {hanzi:"堂",nushu:["𛊤"]},
  {hanzi:"堆",nushu:["𛆬"]},
  {hanzi:"堪",nushu:["𛉲"]},
  {hanzi:"堵",nushu:["𛋦"]},
  {hanzi:"塔",nushu:["𛊔"]},
  {hanzi:"塘",nushu:["𛊤"]},
  {hanzi:"塞",nushu:["𛇴"]},
  {hanzi:"填",nushu:["𛋊"]},
  {hanzi:"墓",nushu:["𛇀"]},
  {hanzi:"墙",nushu:["𛊻","𛈽"]},
  {hanzi:"墨",nushu:["𛋉"]},
  {hanzi:"壁",nushu:["𛉎"]},
  {hanzi:"士",nushu:["𛆹"]},
  {hanzi:"声",nushu:["𛉂"]},
  {hanzi:"壳",nushu:["𛆄"]},
  {hanzi:"壶",nushu:["𛋘"]},
  {hanzi:"处",nushu:["𛉛","𛈫","𛆬"]},
  {hanzi:"备",nushu:["𛊰"]},
  {hanzi:"复",nushu:["𛋷"]},
  {hanzi:"夏",nushu:["𛈣"]},
  {hanzi:"夕",nushu:["𛋮","𛅿"]},
  {hanzi:"外",nushu:["𛇒","𛇃"]},
  {hanzi:"多",nushu:["𛈁"]},
  {hanzi:"夜",nushu:["𛇩","𛇁","𛆯"]},
  {hanzi:"够",nushu:["𛆅"]},
  {hanzi:"大",nushu:["𛅻"]},
  {hanzi:"天",nushu:["𛆤"]},
  {hanzi:"太",nushu:["𛆎"]},
  {hanzi:"夫",nushu:["𛉖","𛆔"]},
  {hanzi:"央",nushu:["𛈍"]},
  {hanzi:"失",nushu:["𛊼"]},
  {hanzi:"头",nushu:["𛇊"]},
  {hanzi:"奇",nushu:["𛊻","𛆦"]},
  {hanzi:"奈",nushu:["𛉈"]},
  {hanzi:"奉",nushu:["𛉮"]},
  {hanzi:"奏",nushu:["𛊪"]},
  {hanzi:"契",nushu:["𛇬"]},
  {hanzi:"套",nushu:["𛉤","𛇊"]},
  {hanzi:"女",nushu:["𛆁"]},
  {hanzi:"奶",nushu:["𛊊"]},
  {hanzi:"好",nushu:["𛇉","𛆚"]},
  {hanzi:"如",nushu:["𛇄","𛆱"]},
  {hanzi:"妄",nushu:["𛈈"]},
  {hanzi:"妆",nushu:["𛈉"]},
  {hanzi:"妇",nushu:["𛊓","𛇲","𛆖","𛆕"]},
  {hanzi:"妒",nushu:["𛋗"]},
  {hanzi:"妖",nushu:["𛆱"]},
  {hanzi:"妙",nushu:["𛉟"]},
  {hanzi:"妨",nushu:["𛋆","𛋅","𛆠"]},
  {hanzi:"妹",nushu:["𛋉"]},
  {hanzi:"妻",nushu:["𛋴","𛈨"]},
  {hanzi:"妾",nushu:["𛈧"]},
  {hanzi:"姊",nushu:["𛈖"]},
  {hanzi:"始",nushu:["𛇴"]},
  {hanzi:"姑",nushu:["𛋰","𛊿"]},
  {hanzi:"姓",nushu:["𛊮","𛉾"]},
  {hanzi:"姜",nushu:["𛈌"]},
  {hanzi:"姨",nushu:["𛊺"]},
  {hanzi:"姻",nushu:["𛆱"]},
  {hanzi:"姿",nushu:["𛈤"]},
  {hanzi:"威",nushu:["𛆨"]},
  {hanzi:"娇",nushu:["𛋔","𛉒","𛆝"]},
  {hanzi:"娘",nushu:["𛇘"]},
  {hanzi:"娥",nushu:["𛊢"]},
  {hanzi:"娶",nushu:["𛉛","𛇂"]},
  {hanzi:"婆",nushu:["𛉖"]},
  {hanzi:"婚",nushu:["𛆙"]},
  {hanzi:"婢",nushu:["𛊰","𛉎"]},
  {hanzi:"婴",nushu:["𛊫"]},
  {hanzi:"婿",nushu:["𛉅"]},
  {hanzi:"媒",nushu:["𛊬"]},
  {hanzi:"嫁",nushu:["𛉌","𛇧"]},
  {hanzi:"嫂",nushu:["𛊜"]},
  {hanzi:"嫌",nushu:["𛊁"]},
  {hanzi:"嫩",nushu:["𛆫"]},
  {hanzi:"嬉",nushu:["𛋔"]},
  {hanzi:"嬷",nushu:["𛊊","𛇯"]},
  {hanzi:"子",nushu:["𛆑"]},
  {hanzi:"孔",nushu:["𛈋","𛆣"]},
  {hanzi:"孕",nushu:["𛆱"]},
  {hanzi:"字",nushu:["𛈤"]},
  {hanzi:"存",nushu:["𛊶"]},
  {hanzi:"孙",nushu:["𛊍"]},
  {hanzi:"孝",nushu:["𛉬"]},
  {hanzi:"孟",nushu:["𛉟"]},
  {hanzi:"季",nushu:["𛉓"]},
  {hanzi:"孤",nushu:["𛋰","𛋂","𛊿"]},
  {hanzi:"学",nushu:["𛉬"]},
  {hanzi:"孩",nushu:["𛇶"]},
  {hanzi:"孽",nushu:["𛈥"]},
  {hanzi:"宁",nushu:["𛉼","𛉀"]},
  {hanzi:"宅",nushu:["𛊾","𛉊"]},
  {hanzi:"宇",nushu:["𛅷"]},
  {hanzi:"守",nushu:["𛆞","𛆆"]},
  {hanzi:"安",nushu:["𛊃"]},
  {hanzi:"宋",nushu:["𛉡","𛅿"]},
  {hanzi:"完",nushu:["𛆧"]},
  {hanzi:"宗",nushu:["𛈉"]},
  {hanzi:"官",nushu:["𛇕"]},
  {hanzi:"定",nushu:["𛉽"]},
  {hanzi:"宜",nushu:["𛅺"]},
  {hanzi:"宝",nushu:["𛉎"]},
  {hanzi:"实",nushu:["𛋓","𛆹","𛅵"]},
  {hanzi:"室",nushu:["𛊗"]},
  {hanzi:"宫",nushu:["𛈌"]},
  {hanzi:"害",nushu:["𛋚","𛉝","𛇶"]},
  {hanzi:"宵",nushu:["𛈨"]},
  {hanzi:"家",nushu:["𛉊"]},
  {hanzi:"容",nushu:["𛈿"]},
  {hanzi:"宽",nushu:["𛉲"]},
  {hanzi:"宾",nushu:["𛋆"]},
  {hanzi:"宿",nushu:["𛇴","𛅿"]},
  {hanzi:"寂",nushu:["𛋔"]},
  {hanzi:"寄",nushu:["𛉔","𛉓"]},
  {hanzi:"富",nushu:["𛊓","𛆖"]},
  {hanzi:"寒",nushu:["𛊨"]},
  {hanzi:"寡",nushu:["𛉋","𛈅"]},
  {hanzi:"寸",nushu:["𛆄"]},
  {hanzi:"对",nushu:["𛆬"]},
  {hanzi:"寺",nushu:["𛈤"]},
  {hanzi:"寿",nushu:["𛉬"]},
  {hanzi:"封",nushu:["𛋆","𛆠","𛆙"]},
  {hanzi:"射",nushu:["𛊍"]},
  {hanzi:"将",nushu:["𛈼"]},
  {hanzi:"尊",nushu:["𛊶","𛊵"]},
  {hanzi:"小",nushu:["𛅿"]},
  {hanzi:"少",nushu:["𛆿","𛆻"]},
  {hanzi:"尔",nushu:["𛇈"]},
  {hanzi:"尖",nushu:["𛋋"]},
  {hanzi:"尘",nushu:["𛊝"]},
  {hanzi:"尚",nushu:["𛉶"]},
  {hanzi:"尝",nushu:["𛈾"]},
  {hanzi:"尤",nushu:["𛊢"]},
  {hanzi:"就",nushu:["𛉨"]},
  {hanzi:"尸",nushu:["𛊸","𛆹"]},
  {hanzi:"尺",nushu:["𛅼"]},
  {hanzi:"尽",nushu:["𛉑","𛈯"]},
  {hanzi:"尾",nushu:["𛊊"]},
  {hanzi:"尿",nushu:["𛆾"]},
  {hanzi:"层",nushu:["𛋳","𛊪","𛉑"]},
  {hanzi:"居",nushu:["𛋔","𛊵"]},
  {hanzi:"屈",nushu:["𛆩"]},
  {hanzi:"屋",nushu:["𛇱","𛅷"]},
  {hanzi:"屎",nushu:["𛊸"]},
  {hanzi:"展",nushu:["𛊀"]},
  {hanzi:"属",nushu:["𛊼"]},
  {hanzi:"屠",nushu:["𛋥"]},
  {hanzi:"履",nushu:["𛉄"]},
  {hanzi:"山",nushu:["𛇏"]},
  {hanzi:"岁",nushu:["𛊼","𛊮"]},
  {hanzi:"岂",nushu:["𛉛"]},
  {hanzi:"岗",nushu:["𛇕"]},
  {hanzi:"岩",nushu:["𛈕"]},
  {hanzi:"岭",nushu:["𛉼"]},
  {hanzi:"岸",nushu:["𛈀"]},
  {hanzi:"崽",nushu:["𛆑"]},
  {hanzi:"川",nushu:["𛊯"]},
  {hanzi:"州",nushu:["𛆝"]},
  {hanzi:"巡",nushu:["𛊶"]},
  {hanzi:"巢",nushu:["𛋳"]},
  {hanzi:"工",nushu:["𛆃"]},
  {hanzi:"左",nushu:["𛇍"]},
  {hanzi:"差",nushu:["𛊾","𛉉","𛈟"]},
  {hanzi:"己",nushu:["𛆺"]},
  {hanzi:"已",nushu:["𛋤","𛆱"]},
  {hanzi:"巾",nushu:["𛆭"]},
  {hanzi:"市",nushu:["𛆹"]},
  {hanzi:"布",nushu:["𛉖"]},
  {hanzi:"师",nushu:["𛊸","𛆹"]},
  {hanzi:"希",nushu:["𛊼"]},
  {hanzi:"帐",nushu:["𛊪","𛇆"]},
  {hanzi:"帕",nushu:["𛇲"]},
  {hanzi:"帝",nushu:["𛅹"]},
  {hanzi:"带",nushu:["𛊋","𛆒"]},
  {hanzi:"席",nushu:["𛋮"]},
  {hanzi:"帮",nushu:["𛈺"]},
  {hanzi:"常",nushu:["𛈾"]},
  {hanzi:"帽",nushu:["𛉣"]},
  {hanzi:"幅",nushu:["𛋷","𛆕"]},
  {hanzi:"干",nushu:["𛇕","𛆣","𛆉"]},
  {hanzi:"平",nushu:["𛇛","𛆦"]},
  {hanzi:"年",nushu:["𛆥"]},
  {hanzi:"并",nushu:["𛆦"]},
  {hanzi:"幸",nushu:["𛊮","𛇐"]},
  {hanzi:"幼",nushu:["𛈶","𛆱"]},
  {hanzi:"广",nushu:["𛊦","𛇕"]},
  {hanzi:"庄",nushu:["𛈉"]},
  {hanzi:"床",nushu:["𛈉"]},
  {hanzi:"庐",nushu:["𛋗"]},
  {hanzi:"应",nushu:["𛊉","𛆱"]},
  {hanzi:"底",nushu:["𛋒"]},
  {hanzi:"庙",nushu:["𛉟"]},
  {hanzi:"庚",nushu:["𛆃"]},
  {hanzi:"府",nushu:["𛆕"]},
  {hanzi:"度",nushu:["𛋥"]},
  {hanzi:"座",nushu:["𛈱"]},
  {hanzi:"庭",nushu:["𛊭"]},
  {hanzi:"庵",nushu:["𛊃"]},
  {hanzi:"康",nushu:["𛉲"]},
  {hanzi:"延",nushu:["𛋍"]},
  {hanzi:"廷",nushu:["𛊭"]},
  {hanzi:"建",nushu:["𛇝"]},
  {hanzi:"开",nushu:["𛇶"]},
  {hanzi:"弃",nushu:["𛇬"]},
  {hanzi:"弄",nushu:["𛊚","𛆒"]},
  {hanzi:"弓",nushu:["𛈌"]},
  {hanzi:"引",nushu:["𛊉"]},
  {hanzi:"弟",nushu:["𛆒","𛅹"]},
  {hanzi:"张",nushu:["𛈌"]},
  {hanzi:"弯",nushu:["𛈄","𛆨"]},
  {hanzi:"弱",nushu:["𛇩"]},
  {hanzi:"强",nushu:["𛊻"]},
  {hanzi:"归",nushu:["𛈘"]},
  {hanzi:"当",nushu:["𛊥","𛉰"]},
  {hanzi:"形",nushu:["𛊁"]},
  {hanzi:"影",nushu:["𛈇"]},
  {hanzi:"彻",nushu:["𛆻"]},
  {hanzi:"彼",nushu:["𛉎"]},
  {hanzi:"往",nushu:["𛋟","𛉚"]},
  {hanzi:"征",nushu:["𛆭"]},
  {hanzi:"待",nushu:["𛆒","𛅻"]},
  {hanzi:"後",nushu:["𛇌"]},
  {hanzi:"得",nushu:["𛋀","𛆒"]},
  {hanzi:"微",nushu:["𛊄"]},
  {hanzi:"德",nushu:["𛋀"]},
  {hanzi:"徽",nushu:["𛆭"]},
  {hanzi:"心",nushu:["𛊛","𛇺","𛇹"]},
  {hanzi:"忆",nushu:["𛆱"]},
  {hanzi:"忌",nushu:["𛋔","𛉓"]},
  {hanzi:"忍",nushu:["𛅺"]},
  {hanzi:"志",nushu:["𛊝"]},
  {hanzi:"忘",nushu:["𛈈","𛆡"]},
  {hanzi:"忙",nushu:["𛇓"]},
  {hanzi:"忠",nushu:["𛈌"]},
  {hanzi:"忧",nushu:["𛋍","𛇩","𛇁"]},
  {hanzi:"快",nushu:["𛇨"]},
  {hanzi:"念",nushu:["𛉸","𛈏"]},
  {hanzi:"忽",nushu:["𛋷"]},
  {hanzi:"怀",nushu:["𛈝"]},
  {hanzi:"怒",nushu:["𛈏"]},
  {hanzi:"怕",nushu:["𛇲"]},
  {hanzi:"怜",nushu:["𛇇"]},
  {hanzi:"思",nushu:["𛊸"]},
  {hanzi:"怠",nushu:["𛅻"]},
  {hanzi:"急",nushu:["𛋔","𛊐"]},
  {hanzi:"性",nushu:["𛊮","𛉾"]},
  {hanzi:"怨",nushu:["𛋟"]},
  {hanzi:"怪",nushu:["𛋫","𛉌","𛇧"]},
  {hanzi:"总",nushu:["𛋫","𛉨"]},
  {hanzi:"恐",nushu:["𛊩"]},
  {hanzi:"恨",nushu:["𛊲"]},
  {hanzi:"恩",nushu:["𛊸","𛇈"]},
  {hanzi:"恬",nushu:["𛋊"]},
  {hanzi:"恭",nushu:["𛈌"]},
  {hanzi:"息",nushu:["𛅿"]},
  {hanzi:"恶",nushu:["𛉦"]},
  {hanzi:"恼",nushu:["𛈻"]},
  {hanzi:"悔",nushu:["𛋶","𛈣"]},
  {hanzi:"患",nushu:["𛋶","𛆙"]},
  {hanzi:"悬",nushu:["𛈒"]},
  {hanzi:"悯",nushu:["𛇺"]},
  {hanzi:"悲",nushu:["𛊰"]},
  {hanzi:"情",nushu:["𛊭"]},
  {hanzi:"惊",nushu:["𛋭","𛇆","𛆭"]},
  {hanzi:"惜",nushu:["𛊲","𛊈"]},
  {hanzi:"惧",nushu:["𛊖"]},
  {hanzi:"惨",nushu:["𛉒"]},
  {hanzi:"惭",nushu:["𛇆"]},
  {hanzi:"想",nushu:["𛊩"]},
  {hanzi:"惹",nushu:["𛇩"]},
  {hanzi:"愁",nushu:["𛊝"]},
  {hanzi:"意",nushu:["𛋤","𛆱","𛅺"]},
  {hanzi:"愚",nushu:["𛇄"]},
  {hanzi:"感",nushu:["𛊦","𛇕"]},
  {hanzi:"愿",nushu:["𛋟","𛆧"]},
  {hanzi:"慈",nushu:["𛋣"]},
  {hanzi:"慢",nushu:["𛉟"]},
  {hanzi:"憾",nushu:["𛊲"]},
  {hanzi:"懒",nushu:["𛉄"]},
  {hanzi:"戈",nushu:["𛋰"]},
  {hanzi:"戏",nushu:["𛆓"]},
  {hanzi:"成",nushu:["𛈒"]},
  {hanzi:"我",nushu:["𛊉","𛈪","𛈕"]},
  {hanzi:"戒",nushu:["𛆄"]},
  {hanzi:"或",nushu:["𛋶"]},
  {hanzi:"截",nushu:["𛋓"]},
  {hanzi:"户",nushu:["𛆖"]},
  {hanzi:"房",nushu:["𛋅"]},
  {hanzi:"所",nushu:["𛈂"]},
  {hanzi:"扇",nushu:["𛋌","𛉃"]},
  {hanzi:"手",nushu:["𛆞"]},
  {hanzi:"才",nushu:["𛆏"]},
  {hanzi:"扑",nushu:["𛉖"]},
  {hanzi:"托",nushu:["𛈢"]},
  {hanzi:"扛",nushu:["𛆣"]},
  {hanzi:"扣",nushu:["𛆣"]},
  {hanzi:"执",nushu:["𛊐"]},
  {hanzi:"扩",nushu:["𛆄"]},
  {hanzi:"扫",nushu:["𛈗"]},
  {hanzi:"扬",nushu:["𛈿"]},
  {hanzi:"扮",nushu:["𛆙"]},
  {hanzi:"扯",nushu:["𛉝","𛈢"]},
  {hanzi:"扰",nushu:["𛋕"]},
  {hanzi:"扳",nushu:["𛉎"]},
  {hanzi:"扶",nushu:["𛇮"]},
  {hanzi:"批",nushu:["𛅶"]},
  {hanzi:"承",nushu:["𛋙"]},
  {hanzi:"抄",nushu:["𛋴"]},
  {hanzi:"把",nushu:["𛊷","𛉎","𛇪"]},
  {hanzi:"抑",nushu:["𛋍"]},
  {hanzi:"投",nushu:["𛇊"]},
  {hanzi:"抖",nushu:["𛆛"]},
  {hanzi:"折",nushu:["𛊐"]},
  {hanzi:"抛",nushu:["𛈲","𛇾"]},
  {hanzi:"抢",nushu:["𛊩","𛉱"]},
  {hanzi:"报",nushu:["𛇣"]},
  {hanzi:"披",nushu:["𛅶"]},
  {hanzi:"抬",nushu:["𛅻"]},
  {hanzi:"抱",nushu:["𛉖"]},
  {hanzi:"抵",nushu:["𛋒"]},
  {hanzi:"抽",nushu:["𛆝"]},
  {hanzi:"拄",nushu:["𛉙"]},
  {hanzi:"担",nushu:["𛉻"]},
  {hanzi:"拆",nushu:["𛋓"]},
  {hanzi:"拉",nushu:["𛆒"]},
  {hanzi:"拍",nushu:["𛇲","𛇫","𛇪"]},
  {hanzi:"拐",nushu:["𛋫"]},
  {hanzi:"拔",nushu:["𛊰","𛉜","𛇫","𛇣"]},
  {hanzi:"拖",nushu:["𛈢"]},
  {hanzi:"招",nushu:["𛋔"]},
  {hanzi:"拜",nushu:["𛇣"]},
  {hanzi:"拨",nushu:["𛇲","𛇫"]},
  {hanzi:"括",nushu:["𛆐"]},
  {hanzi:"拯",nushu:["𛇆"]},
  {hanzi:"拳",nushu:["𛈆"]},
  {hanzi:"拼",nushu:["𛈐","𛆦"]},
  {hanzi:"拾",nushu:["𛅵"]},
  {hanzi:"拿",nushu:["𛇁"]},
  {hanzi:"持",nushu:["𛋣"]},
  {hanzi:"挂",nushu:["𛋫","𛉌"]},
  {hanzi:"指",nushu:["𛋓","𛆑"]},
  {hanzi:"挖",nushu:["𛋢"]},
  {hanzi:"挡",nushu:["𛊥"]},
  {hanzi:"挥",nushu:["𛆌"]},
  {hanzi:"挪",nushu:["𛉈"]},
  {hanzi:"捉",nushu:["𛊋"]},
  {hanzi:"捐",nushu:["𛉉"]},
  {hanzi:"损",nushu:["𛉝"]},
  {hanzi:"捡",nushu:["𛊀"]},
  {hanzi:"换",nushu:["𛊧"]},
  {hanzi:"捨",nushu:["𛉝"]},
  {hanzi:"掀",nushu:["𛉃"]},
  {hanzi:"授",nushu:["𛉬"]},
  {hanzi:"掌",nushu:["𛇗"]},
  {hanzi:"排",nushu:["𛉆"]},
  {hanzi:"探",nushu:["𛋃"]},
  {hanzi:"接",nushu:["𛋓"]},
  {hanzi:"推",nushu:["𛋴","𛉘"]},
  {hanzi:"掰",nushu:["𛋆"]},
  {hanzi:"掳",nushu:["𛋗"]},
  {hanzi:"提",nushu:["𛊹"]},
  {hanzi:"插",nushu:["𛇦"]},
  {hanzi:"揩",nushu:["𛉌","𛇧"]},
  {hanzi:"援",nushu:["𛆧"]},
  {hanzi:"搁",nushu:["𛉦","𛇿"]},
  {hanzi:"搞",nushu:["𛇉"]},
  {hanzi:"搬",nushu:["𛈺"]},
  {hanzi:"搽",nushu:["𛉗"]},
  {hanzi:"摆",nushu:["𛉎","𛇣"]},
  {hanzi:"摇",nushu:["𛊺"]},
  {hanzi:"摘",nushu:["𛋓"]},
  {hanzi:"摩",nushu:["𛋪"]},
  {hanzi:"摸",nushu:["𛋪"]},
  {hanzi:"撑",nushu:["𛊝","𛊌","𛇗"]},
  {hanzi:"撞",nushu:["𛈉"]},
  {hanzi:"操",nushu:["𛋴","𛊾"]},
  {hanzi:"支",nushu:["𛈤","𛆷"]},
  {hanzi:"收",nushu:["𛈀"]},
  {hanzi:"改",nushu:["𛊿","𛇧"]},
  {hanzi:"放",nushu:["𛉮","𛈺"]},
  {hanzi:"政",nushu:["𛇆"]},
  {hanzi:"故",nushu:["𛉘","𛇰"]},
  {hanzi:"效",nushu:["𛉬"]},
  {hanzi:"敌",nushu:["𛋮"]},
  {hanzi:"敏",nushu:["𛋉"]},
  {hanzi:"救",nushu:["𛆝"]},
  {hanzi:"教",nushu:["𛆝"]},
  {hanzi:"敢",nushu:["𛊦","𛇕"]},
  {hanzi:"散",nushu:["𛈗"]},
  {hanzi:"敬",nushu:["𛇝","𛇆"]},
  {hanzi:"数",nushu:["𛉅"]},
  {hanzi:"敲",nushu:["𛋂"]},
  {hanzi:"整",nushu:["𛇆"]},
  {hanzi:"文",nushu:["𛆂"]},
  {hanzi:"斋",nushu:["𛊳","𛉑"]},
  {hanzi:"斑",nushu:["𛊰"]},
  {hanzi:"斗",nushu:["𛇼","𛆛"]},
  {hanzi:"料",nushu:["𛆽"]},
  {hanzi:"斟",nushu:["𛆭"]},
  {hanzi:"斤",nushu:["𛆭"]},
  {hanzi:"斧",nushu:["𛋷","𛊒"]},
  {hanzi:"断",nushu:["𛋈","𛋇","𛊥"]},
  {hanzi:"斯",nushu:["𛊸"]},
  {hanzi:"新",nushu:["𛊛","𛇺","𛇹"]},
  {hanzi:"方",nushu:["𛆠"]},
  {hanzi:"施",nushu:["𛊸"]},
  {hanzi:"旁",nushu:["𛋅"]},
  {hanzi:"旅",nushu:["𛆽"]},
  {hanzi:"旗",nushu:["𛊻"]},
  {hanzi:"无",nushu:["𛇯"]},
  {hanzi:"既",nushu:["𛋤","𛉓","𛇬"]},
  {hanzi:"日",nushu:["𛇈","𛅱"]},
  {hanzi:"旦",nushu:["𛉄"]},
  {hanzi:"旧",nushu:["𛆝"]},
  {hanzi:"旨",nushu:["𛆑"]},
  {hanzi:"早",nushu:["𛈖"]},
  {hanzi:"旱",nushu:["𛊧"]},
  {hanzi:"时",nushu:["𛆸"]},
  {hanzi:"明",nushu:["𛇾"]},
  {hanzi:"昏",nushu:["𛆙"]},
  {hanzi:"易",nushu:["𛆱"]},
  {hanzi:"昔",nushu:["𛊲","𛊈"]},
  {hanzi:"星",nushu:["𛉾"]},
  {hanzi:"映",nushu:["𛈇"]},
  {hanzi:"春",nushu:["𛊌"]},
  {hanzi:"昨",nushu:["𛋳","𛈱"]},
  {hanzi:"是",nushu:["𛇴","𛆹","𛅵"]},
  {hanzi:"昼",nushu:["𛆝"]},
  {hanzi:"显",nushu:["𛉃"]},
  {hanzi:"晒",nushu:["𛈗"]},
  {hanzi:"晡",nushu:["𛉖"]},
  {hanzi:"晨",nushu:["𛋙"]},
  {hanzi:"景",nushu:["𛇆"]},
  {hanzi:"晴",nushu:["𛊭"]},
  {hanzi:"智",nushu:["𛊝"]},
  {hanzi:"暑",nushu:["𛋱"]},
  {hanzi:"暖",nushu:["𛈾"]},
  {hanzi:"暗",nushu:["𛈕"]},
  {hanzi:"曰",nushu:["𛆴"]},
  {hanzi:"曲",nushu:["𛆶"]},
  {hanzi:"更",nushu:["𛋫","𛉘","𛈸","𛆃"]},
  {hanzi:"曹",nushu:["𛋳","𛊝"]},
  {hanzi:"曾",nushu:["𛋳","𛇴","𛆒"]},
  {hanzi:"替",nushu:["𛉕","𛆒"]},
  {hanzi:"最",nushu:["𛊶"]},
  {hanzi:"月",nushu:["𛇃"]},
  {hanzi:"有",nushu:["𛈶"]},
  {hanzi:"朋",nushu:["𛊘"]},
  {hanzi:"服",nushu:["𛈩","𛆖"]},
  {hanzi:"朗",nushu:["𛊥"]},
  {hanzi:"望",nushu:["𛈈"]},
  {hanzi:"朝",nushu:["𛋔","𛊻","𛆦","𛅾"]},
  {hanzi:"期",nushu:["𛊻"]},
  {hanzi:"木",nushu:["𛇀"]},
  {hanzi:"未",nushu:["𛆳","𛆨"]},
  {hanzi:"本",nushu:["𛇅"]},
  {hanzi:"朱",nushu:["𛉙"]},
  {hanzi:"机",nushu:["𛋔"]},
  {hanzi:"杀",nushu:["𛇦"]},
  {hanzi:"权",nushu:["𛈆"]},
  {hanzi:"杆",nushu:["𛇕","𛆣"]},
  {hanzi:"杉",nushu:["𛊾"]},
  {hanzi:"李",nushu:["𛉄"]},
  {hanzi:"杏",nushu:["𛇐"]},
  {hanzi:"村",nushu:["𛊌"]},
  {hanzi:"杠",nushu:["𛆣"]},
  {hanzi:"来",nushu:["𛇤"]},
  {hanzi:"杨",nushu:["𛈿"]},
  {hanzi:"杭",nushu:["𛊨"]},
  {hanzi:"杯",nushu:["𛇲"]},
  {hanzi:"松",nushu:["𛉵"]},
  {hanzi:"板",nushu:["𛉎"]},
  {hanzi:"极",nushu:["𛋔"]},
  {hanzi:"枉",nushu:["𛉯","𛈈"]},
  {hanzi:"枕",nushu:["𛆻"]},
  {hanzi:"林",nushu:["𛇇"]},
  {hanzi:"枚",nushu:["𛋉","𛊬"]},
  {hanzi:"果",nushu:["𛈅","𛇰"]},
  {hanzi:"枝",nushu:["𛈤"]},
  {hanzi:"枪",nushu:["𛉱"]},
  {hanzi:"枯",nushu:["𛇰"]},
  {hanzi:"架",nushu:["𛉌","𛇧"]},
  {hanzi:"柏",nushu:["𛇫"]},
  {hanzi:"柑",nushu:["𛇕"]},
  {hanzi:"染",nushu:["𛊫"]},
  {hanzi:"柔",nushu:["𛊢"]},
  {hanzi:"查",nushu:["𛉗"]},
  {hanzi:"柱",nushu:["𛇭"]},
  {hanzi:"柳",nushu:["𛇋"]},
  {hanzi:"栅",nushu:["𛈊"]},
  {hanzi:"标",nushu:["𛅶"]},
  {hanzi:"栋",nushu:["𛊥"]},
  {hanzi:"树",nushu:["𛋙","𛈬"]},
  {hanzi:"校",nushu:["𛉬"]},
  {hanzi:"样",nushu:["𛈍"]},
  {hanzi:"根",nushu:["𛆃"]},
  {hanzi:"格",nushu:["𛈅"]},
  {hanzi:"栽",nushu:["𛇥"]},
  {hanzi:"桂",nushu:["𛋫","𛉓"]},
  {hanzi:"桃",nushu:["𛊤"]},
  {hanzi:"案",nushu:["𛈕"]},
  {hanzi:"桑",nushu:["𛈊"]},
  {hanzi:"桥",nushu:["𛊻","𛆦"]},
  {hanzi:"桩",nushu:["𛈉"]},
  {hanzi:"桶",nushu:["𛋒"]},
  {hanzi:"梁",nushu:["𛉴"]},
  {hanzi:"梅",nushu:["𛋉","𛊬"]},
  {hanzi:"梦",nushu:["𛋪"]},
  {hanzi:"梭",nushu:["𛇏"]},
  {hanzi:"梯",nushu:["𛊏"]},
  {hanzi:"梳",nushu:["𛊾"]},
  {hanzi:"棉",nushu:["𛊬"]},
  {hanzi:"棋",nushu:["𛊻","𛆦"]},
  {hanzi:"棍",nushu:["𛋫"]},
  {hanzi:"棠",nushu:["𛊤"]},
  {hanzi:"森",nushu:["𛇹"]},
  {hanzi:"棺",nushu:["𛇕"]},
  {hanzi:"椅",nushu:["𛋕"]},
  {hanzi:"植",nushu:["𛉓"]},
  {hanzi:"椒",nushu:["𛊑"]},
  {hanzi:"楚",nushu:["𛉤"]},
  {hanzi:"楼",nushu:["𛈰"]},
  {hanzi:"榜",nushu:["𛉎"]},
  {hanzi:"榴",nushu:["𛇋"]},
  {hanzi:"榻",nushu:["𛋥"]},
  {hanzi:"樟",nushu:["𛈌"]},
  {hanzi:"樵",nushu:["𛉑","𛇭"]},
  {hanzi:"次",nushu:["𛇠"]},
  {hanzi:"欢",nushu:["𛊧"]},
  {hanzi:"欧",nushu:["𛉧"]},
  {hanzi:"欲",nushu:["𛉚","𛇄"]},
  {hanzi:"欺",nushu:["𛊼","𛇂"]},
  {hanzi:"歇",nushu:["𛊗"]},
  {hanzi:"歌",nushu:["𛋸","𛋰"]},
  {hanzi:"正",nushu:["𛋭","𛇆"]},
  {hanzi:"此",nushu:["𛇠","𛆑"]},
  {hanzi:"步",nushu:["𛉖"]},
  {hanzi:"武",nushu:["𛇯","𛅷"]},
  {hanzi:"死",nushu:["𛊅","𛇦"]},
  {hanzi:"殊",nushu:["𛋙"]},
  {hanzi:"残",nushu:["𛉒"]},
  {hanzi:"段",nushu:["𛋇"]},
  {hanzi:"殷",nushu:["𛆱"]},
  {hanzi:"殿",nushu:["𛋊"]},
  {hanzi:"母",nushu:["𛇀"]},
  {hanzi:"每",nushu:["𛉟"]},
  {hanzi:"毑",nushu:["𛇡"]},
  {hanzi:"毒",nushu:["𛋥"]},
  {hanzi:"比",nushu:["𛉎"]},
  {hanzi:"毛",nushu:["𛇷"]},
  {hanzi:"毫",nushu:["𛈨","𛇮"]},
  {hanzi:"氏",nushu:["𛆹"]},
  {hanzi:"民",nushu:["𛇷"]},
  {hanzi:"气",nushu:["𛇬"]},
  {hanzi:"水",nushu:["𛅸"]},
  {hanzi:"汁",nushu:["𛊐"]},
  {hanzi:"求",nushu:["𛆝"]},
  {hanzi:"汉",nushu:["𛊧"]},
  {hanzi:"汗",nushu:["𛊧"]},
  {hanzi:"江",nushu:["𛈌"]},
  {hanzi:"池",nushu:["𛋣","𛆑"]},
  {hanzi:"污",nushu:["𛉍","𛆱"]},
  {hanzi:"汤",nushu:["𛇔","𛆤"]},
  {hanzi:"汪",nushu:["𛈈","𛇼"]},
  {hanzi:"沈",nushu:["𛆭"]},
  {hanzi:"沉",nushu:["𛋳","𛊝"]},
  {hanzi:"沙",nushu:["𛊾"]},
  {hanzi:"沟",nushu:["𛋂"]},
  {hanzi:"没",nushu:["𛆋"]},
  {hanzi:"河",nushu:["𛋘","𛊕"]},
  {hanzi:"沸",nushu:["𛇣"]},
  {hanzi:"油",nushu:["𛊺","𛊢"]},
  {hanzi:"治",nushu:["𛊝"]},
  {hanzi:"沾",nushu:["𛊀"]},
  {hanzi:"泉",nushu:["𛋋","𛈆"]},
  {hanzi:"法",nushu:["𛊡"]},
  {hanzi:"泥",nushu:["𛈥","𛆰"]},
  {hanzi:"注",nushu:["𛉓"]},
  {hanzi:"泪",nushu:["𛇟","𛆍"]},
  {hanzi:"泼",nushu:["𛇫"]},
  {hanzi:"洁",nushu:["𛊐"]},
  {hanzi:"洋",nushu:["𛈿"]},
  {hanzi:"洗",nushu:["𛅿"]},
  {hanzi:"洛",nushu:["𛋝","𛈁"]},
  {hanzi:"洞",nushu:["𛆒"]},
  {hanzi:"洪",nushu:["𛉢"]},
  {hanzi:"洲",nushu:["𛆝"]},
  {hanzi:"活",nushu:["𛋶"]},
  {hanzi:"派",nushu:["𛈜","𛇢"]},
  {hanzi:"流",nushu:["𛇋"]},
  {hanzi:"浅",nushu:["𛋋","𛈉"]},
  {hanzi:"浆",nushu:["𛈼"]},
  {hanzi:"浊",nushu:["𛈱"]},
  {hanzi:"济",nushu:["𛉒"]},
  {hanzi:"浪",nushu:["𛋈"]},
  {hanzi:"浮",nushu:["𛊘"]},
  {hanzi:"海",nushu:["𛉝"]},
  {hanzi:"浸",nushu:["𛋎"]},
  {hanzi:"消",nushu:["𛈨"]},
  {hanzi:"涨",nushu:["𛈌"]},
  {hanzi:"淋",nushu:["𛇇"]},
  {hanzi:"淑",nushu:["𛊼"]},
  {hanzi:"淡",nushu:["𛋠"]},
  {hanzi:"深",nushu:["𛋙","𛈛"]},
  {hanzi:"清",nushu:["𛊭"]},
  {hanzi:"渊",nushu:["𛋟"]},
  {hanzi:"渐",nushu:["𛋺","𛊻","𛇆"]},
  {hanzi:"渔",nushu:["𛊢"]},
  {hanzi:"渡",nushu:["𛋥"]},
  {hanzi:"游",nushu:["𛊺","𛊢"]},
  {hanzi:"湖",nushu:["𛋘","𛇰"]},
  {hanzi:"湘",nushu:["𛉵"]},
  {hanzi:"湾",nushu:["𛈄","𛆨"]},
  {hanzi:"源",nushu:["𛆧"]},
  {hanzi:"溜",nushu:["𛇋"]},
  {hanzi:"滋",nushu:["𛈤","𛆷"]},
  {hanzi:"滑",nushu:["𛇵"]},
  {hanzi:"滔",nushu:["𛋃"]},
  {hanzi:"滚",nushu:["𛈅"]},
  {hanzi:"满",nushu:["𛋪"]},
  {hanzi:"滩",nushu:["𛉭"]},
  {hanzi:"滴",nushu:["𛆒"]},
  {hanzi:"漂",nushu:["𛅶"]},
  {hanzi:"漏",nushu:["𛋧"]},
  {hanzi:"潭",nushu:["𛋠","𛆒"]},
  {hanzi:"澡",nushu:["𛈖"]},
  {hanzi:"火",nushu:["𛆕"]},
  {hanzi:"灯",nushu:["𛊚","𛆒"]},
  {hanzi:"灰",nushu:["𛈣","𛆌"]},
  {hanzi:"灵",nushu:["𛉼","𛉀"]},
  {hanzi:"灶",nushu:["𛊪"]},
  {hanzi:"灾",nushu:["𛊳","𛇥"]},
  {hanzi:"炉",nushu:["𛋗"]},
  {hanzi:"炎",nushu:["𛋍"]},
  {hanzi:"炒",nushu:["𛉤"]},
  {hanzi:"炕",nushu:["𛆣"]},
  {hanzi:"炙",nushu:["𛊶"]},
  {hanzi:"炭",nushu:["𛈃"]},
  {hanzi:"点",nushu:["𛉸"]},
  {hanzi:"炼",nushu:["𛈏"]},
  {hanzi:"烘",nushu:["𛇕"]},
  {hanzi:"烛",nushu:["𛅼"]},
  {hanzi:"烟",nushu:["𛊫"]},
  {hanzi:"烦",nushu:["𛊨","𛇐"]},
  {hanzi:"烧",nushu:["𛊼"]},
  {hanzi:"热",nushu:["𛈥"]},
  {hanzi:"焕",nushu:["𛊧"]},
  {hanzi:"焦",nushu:["𛊑"]},
  {hanzi:"然",nushu:["𛋋","𛈔","𛆥"]},
  {hanzi:"煞",nushu:["𛇦"]},
  {hanzi:"照",nushu:["𛉔","𛉓"]},
  {hanzi:"煮",nushu:["𛋒","𛆗"]},
  {hanzi:"熊",nushu:["𛈾"]},
  {hanzi:"熟",nushu:["𛉬"]},
  {hanzi:"燃",nushu:["𛆥"]},
  {hanzi:"燕",nushu:["𛊂"]},
  {hanzi:"爪",nushu:["𛆺"]},
  {hanzi:"爱",nushu:["𛋨"]},
  {hanzi:"父",nushu:["𛆖"]},
  {hanzi:"爷",nushu:["𛉍"]},
  {hanzi:"爹",nushu:["𛉍"]},
  {hanzi:"片",nushu:["𛇙","𛅶"]},
  {hanzi:"牙",nushu:["𛊢"]},
  {hanzi:"牛",nushu:["𛊞","𛈰"]},
  {hanzi:"牡",nushu:["𛇀"]},
  {hanzi:"物",nushu:["𛇵"]},
  {hanzi:"牲",nushu:["𛇏"]},
  {hanzi:"牵",nushu:["𛈢"]},
  {hanzi:"犀",nushu:["𛈨"]},
  {hanzi:"犁",nushu:["𛅾"]},
  {hanzi:"犯",nushu:["𛊮"]},
  {hanzi:"状",nushu:["𛈉"]},
  {hanzi:"犹",nushu:["𛊢"]},
  {hanzi:"狗",nushu:["𛆄"]},
  {hanzi:"独",nushu:["𛋥"]},
  {hanzi:"狮",nushu:["𛊸","𛆹"]},
  {hanzi:"狼",nushu:["𛊥"]},
  {hanzi:"猜",nushu:["𛈟"]},
  {hanzi:"猪",nushu:["𛆽"]},
  {hanzi:"猫",nushu:["𛋓"]},
  {hanzi:"玉",nushu:["𛉚"]},
  {hanzi:"王",nushu:["𛆧"]},
  {hanzi:"玩",nushu:["𛋅","𛆧"]},
  {hanzi:"环",nushu:["𛋅"]},
  {hanzi:"现",nushu:["𛋌","𛉃"]},
  {hanzi:"玻",nushu:["𛉖"]},
  {hanzi:"珍",nushu:["𛆭"]},
  {hanzi:"珠",nushu:["𛉙"]},
  {hanzi:"球",nushu:["𛆝"]},
  {hanzi:"理",nushu:["𛉄"]},
  {hanzi:"琴",nushu:["𛊝"]},
  {hanzi:"瑜",nushu:["𛆱"]},
  {hanzi:"璃",nushu:["𛊎"]},
  {hanzi:"瓜",nushu:["𛉊"]},
  {hanzi:"瓦",nushu:["𛈪"]},
  {hanzi:"瓶",nushu:["𛇛","𛆦"]},
  {hanzi:"甘",nushu:["𛇕"]},
  {hanzi:"甚",nushu:["𛋐"]},
  {hanzi:"甜",nushu:["𛋊"]},
  {hanzi:"生",nushu:["𛇏"]},
  {hanzi:"甥",nushu:["𛇏"]},
  {hanzi:"用",nushu:["𛈍"]},
  {hanzi:"甫",nushu:["𛉖"]},
  {hanzi:"田",nushu:["𛋊","𛈎"]},
  {hanzi:"由",nushu:["𛊢"]},
  {hanzi:"甲",nushu:["𛈅"]},
  {hanzi:"申",nushu:["𛈛"]},
  {hanzi:"电",nushu:["𛋊"]},
  {hanzi:"男",nushu:["𛉺"]},
  {hanzi:"画",nushu:["𛋶","𛈣"]},
  {hanzi:"界",nushu:["𛆅","𛆄"]},
  {hanzi:"留",nushu:["𛇋"]},
  {hanzi:"畜",nushu:["𛉩"]},
  {hanzi:"略",nushu:["𛆜"]},
  {hanzi:"番",nushu:["𛆠","𛆌"]},
  {hanzi:"疆",nushu:["𛈌"]},
  {hanzi:"疏",nushu:["𛊾"]},
  {hanzi:"病",nushu:["𛈐"]},
  {hanzi:"痛",nushu:["𛋃"]},
  {hanzi:"痴",nushu:["𛊼"]},
  {hanzi:"瘦",nushu:["𛈗"]},
  {hanzi:"癞",nushu:["𛉘"]},
  {hanzi:"癸",nushu:["𛈙"]},
  {hanzi:"登",nushu:["𛊚","𛆒"]},
  {hanzi:"白",nushu:["𛇪"]},
  {hanzi:"百",nushu:["𛇫"]},
  {hanzi:"皂",nushu:["𛊪","𛈯"]},
  {hanzi:"的",nushu:["𛉘"]},
  {hanzi:"皆",nushu:["𛉌","𛇧"]},
  {hanzi:"皇",nushu:["𛊨"]},
  {hanzi:"皮",nushu:["𛇣"]},
  {hanzi:"皱",nushu:["𛊪","𛊑"]},
  {hanzi:"盆",nushu:["𛊘"]},
  {hanzi:"盈",nushu:["𛋍"]},
  {hanzi:"益",nushu:["𛇩"]},
  {hanzi:"盏",nushu:["𛈖"]},
  {hanzi:"盐",nushu:["𛋍"]},
  {hanzi:"盖",nushu:["𛉘","𛇧"]},
  {hanzi:"盘",nushu:["𛋅"]},
  {hanzi:"盛",nushu:["𛈒"]},
  {hanzi:"目",nushu:["𛇀"]},
  {hanzi:"盲",nushu:["𛇓"]},
  {hanzi:"直",nushu:["𛋔","𛋓","𛉓"]},
  {hanzi:"相",nushu:["𛊩","𛉵","𛈼","𛇐"]},
  {hanzi:"省",nushu:["𛊜","𛇠"]},
  {hanzi:"眉",nushu:["𛇷","𛇓"]},
  {hanzi:"看",nushu:["𛆣"]},
  {hanzi:"真",nushu:["𛆭"]},
  {hanzi:"眠",nushu:["𛊬"]},
  {hanzi:"眯",nushu:["𛉟","𛇓"]},
  {hanzi:"眷",nushu:["𛋺","𛇆"]},
  {hanzi:"眼",nushu:["𛋵"]},
  {hanzi:"着",nushu:["𛊖"]},
  {hanzi:"睛",nushu:["𛉽"]},
  {hanzi:"睡",nushu:["𛉅","𛆙"]},
  {hanzi:"瞒",nushu:["𛇓"]},
  {hanzi:"知",nushu:["𛇟","𛆍"]},
  {hanzi:"矩",nushu:["𛆗"]},
  {hanzi:"短",nushu:["𛋈","𛋇","𛊥"]},
  {hanzi:"矮",nushu:["𛊴"]},
  {hanzi:"石",nushu:["𛊍"]},
  {hanzi:"砌",nushu:["𛆻"]},
  {hanzi:"砍",nushu:["𛉳","𛆣"]},
  {hanzi:"研",nushu:["𛈏"]},
  {hanzi:"砚",nushu:["𛈏"]},
  {hanzi:"破",nushu:["𛉖"]},
  {hanzi:"硕",nushu:["𛊗"]},
  {hanzi:"硬",nushu:["𛈕"]},
  {hanzi:"确",nushu:["𛆄"]},
  {hanzi:"碑",nushu:["𛊰"]},
  {hanzi:"碗",nushu:["𛊃","𛈕"]},
  {hanzi:"碟",nushu:["𛋮"]},
  {hanzi:"磨",nushu:["𛊃","𛇀"]},
  {hanzi:"示",nushu:["𛆹"]},
  {hanzi:"礼",nushu:["𛅹"]},
  {hanzi:"社",nushu:["𛊍"]},
  {hanzi:"祀",nushu:["𛊖"]},
  {hanzi:"祁",nushu:["𛊻"]},
  {hanzi:"祖",nushu:["𛊽"]},
  {hanzi:"祝",nushu:["𛉫"]},
  {hanzi:"神",nushu:["𛋙"]},
  {hanzi:"祥",nushu:["𛈽"]},
  {hanzi:"祭",nushu:["𛉒","𛈯"]},
  {hanzi:"祸",nushu:["𛊓","𛆖"]},
  {hanzi:"禁",nushu:["𛊝"]},
  {hanzi:"禄",nushu:["𛋗"]},
  {hanzi:"福",nushu:["𛋷","𛆖"]},
  {hanzi:"离",nushu:["𛊎"]},
  {hanzi:"禾",nushu:["𛇯"]},
  {hanzi:"秀",nushu:["𛋜"]},
  {hanzi:"私",nushu:["𛊸"]},
  {hanzi:"秋",nushu:["𛉩"]},
  {hanzi:"种",nushu:["𛊪","𛊝","𛉔","𛆻"]},
  {hanzi:"科",nushu:["𛋰"]},
  {hanzi:"租",nushu:["𛊾"]},
  {hanzi:"秦",nushu:["𛉒"]},
  {hanzi:"秧",nushu:["𛊫"]},
  {hanzi:"积",nushu:["𛊈"]},
  {hanzi:"称",nushu:["𛆮","𛆒"]},
  {hanzi:"移",nushu:["𛊺","𛇄"]},
  {hanzi:"稀",nushu:["𛊼"]},
  {hanzi:"程",nushu:["𛈆"]},
  {hanzi:"稍",nushu:["𛆿"]},
  {hanzi:"稳",nushu:["𛇒"]},
  {hanzi:"稻",nushu:["𛋛","𛇼"]},
  {hanzi:"稽",nushu:["𛋔"]},
  {hanzi:"稿",nushu:["𛋂","𛆄"]},
  {hanzi:"穀",nushu:["𛋸"]},
  {hanzi:"究",nushu:["𛆝"]},
  {hanzi:"穷",nushu:["𛊝"]},
  {hanzi:"空",nushu:["𛉲"]},
  {hanzi:"穿",nushu:["𛊯"]},
  {hanzi:"窑",nushu:["𛊺"]},
  {hanzi:"窗",nushu:["𛉱"]},
  {hanzi:"窝",nushu:["𛉯","𛉚"]},
  {hanzi:"窦",nushu:["𛋥"]},
  {hanzi:"立",nushu:["𛇟","𛆍"]},
  {hanzi:"竖",nushu:["𛋙"]},
  {hanzi:"站",nushu:["𛉓"]},
  {hanzi:"竟",nushu:["𛇆"]},
  {hanzi:"章",nushu:["𛈌"]},
  {hanzi:"童",nushu:["𛊤"]},
  {hanzi:"端",nushu:["𛋈","𛋇","𛊥","𛉰"]},
  {hanzi:"竹",nushu:["𛊶"]},
  {hanzi:"竿",nushu:["𛆃"]},
  {hanzi:"笋",nushu:["𛊍","𛉝"]},
  {hanzi:"笑",nushu:["𛅿"]},
  {hanzi:"笔",nushu:["𛇞"]},
  {hanzi:"笙",nushu:["𛇏"]},
  {hanzi:"笛",nushu:["𛋮"]},
  {hanzi:"笠",nushu:["𛇟"]},
  {hanzi:"第",nushu:["𛆒"]},
  {hanzi:"等",nushu:["𛉠"]},
  {hanzi:"筋",nushu:["𛆭"]},
  {hanzi:"答",nushu:["𛋀"]},
  {hanzi:"策",nushu:["𛋓"]},
  {hanzi:"筹",nushu:["𛆝"]},
  {hanzi:"签",nushu:["𛆉"]},
  {hanzi:"算",nushu:["𛆢"]},
  {hanzi:"管",nushu:["𛊦","𛇕"]},
  {hanzi:"箭",nushu:["𛋋"]},
  {hanzi:"箱",nushu:["𛉵"]},
  {hanzi:"篇",nushu:["𛈐"]},
  {hanzi:"篙",nushu:["𛋂"]},
  {hanzi:"篮",nushu:["𛋂"]},
  {hanzi:"篱",nushu:["𛊎"]},
  {hanzi:"簪",nushu:["𛉾"]},
  {hanzi:"米",nushu:["𛉟"]},
  {hanzi:"粉",nushu:["𛆙"]},
  {hanzi:"粒",nushu:["𛆍"]},
  {hanzi:"粗",nushu:["𛊾"]},
  {hanzi:"粟",nushu:["𛈬"]},
  {hanzi:"粥",nushu:["𛉫"]},
  {hanzi:"粪",nushu:["𛆙"]},
  {hanzi:"粮",nushu:["𛉴"]},
  {hanzi:"粱",nushu:["𛉴"]},
  {hanzi:"精",nushu:["𛋭","𛉽"]},
  {hanzi:"糕",nushu:["𛋂"]},
  {hanzi:"糠",nushu:["𛊧"]},
  {hanzi:"系",nushu:["𛆱"]},
  {hanzi:"紧",nushu:["𛆻"]},
  {hanzi:"紫",nushu:["𛆑"]},
  {hanzi:"纠",nushu:["𛆝"]},
  {hanzi:"红",nushu:["𛉢"]},
  {hanzi:"约",nushu:["𛆴","𛅷"]},
  {hanzi:"级",nushu:["𛊐"]},
  {hanzi:"纪",nushu:["𛉓","𛆺"]},
  {hanzi:"纱",nushu:["𛊾"]},
  {hanzi:"纵",nushu:["𛈼"]},
  {hanzi:"纷",nushu:["𛆙"]},
  {hanzi:"纸",nushu:["𛆑"]},
  {hanzi:"纺",nushu:["𛋅"]},
  {hanzi:"线",nushu:["𛉹"]},
  {hanzi:"练",nushu:["𛈏"]},
  {hanzi:"组",nushu:["𛊽"]},
  {hanzi:"细",nushu:["𛅿"]},
  {hanzi:"织",nushu:["𛊐"]},
  {hanzi:"终",nushu:["𛈌"]},
  {hanzi:"绍",nushu:["𛋙"]},
  {hanzi:"经",nushu:["𛉿"]},
  {hanzi:"绒",nushu:["𛈿"]},
  {hanzi:"结",nushu:["𛊐"]},
  {hanzi:"给",nushu:["𛋶"]},
  {hanzi:"绝",nushu:["𛋔"]},
  {hanzi:"绞",nushu:["𛆝"]},
  {hanzi:"统",nushu:["𛊤"]},
  {hanzi:"绣",nushu:["𛋜"]},
  {hanzi:"继",nushu:["𛉓"]},
  {hanzi:"绩",nushu:["𛊈"]},
  {hanzi:"绪",nushu:["𛉓"]},
  {hanzi:"维",nushu:["𛊄"]},
  {hanzi:"绵",nushu:["𛊬"]},
  {hanzi:"绸",nushu:["𛉨"]},
  {hanzi:"综",nushu:["𛇎"]},
  {hanzi:"绿",nushu:["𛆽"]},
  {hanzi:"缎",nushu:["𛋇"]},
  {hanzi:"缘",nushu:["𛆧"]},
  {hanzi:"缠",nushu:["𛊀","𛉉","𛈆"]},
  {hanzi:"缴",nushu:["𛆺"]},
  {hanzi:"缸",nushu:["𛇕"]},
  {hanzi:"缽",nushu:["𛇫"]},
  {hanzi:"罐",nushu:["𛇿"]},
  {hanzi:"网",nushu:["𛋪"]},
  {hanzi:"罗",nushu:["𛊎"]},
  {hanzi:"罚",nushu:["𛋶"]},
  {hanzi:"罪",nushu:["𛊶"]},
  {hanzi:"置",nushu:["𛋔"]},
  {hanzi:"羊",nushu:["𛈿"]},
  {hanzi:"美",nushu:["𛋪"]},
  {hanzi:"羞",nushu:["𛉪"]},
  {hanzi:"羽",nushu:["𛅷"]},
  {hanzi:"翅",nushu:["𛆑"]},
  {hanzi:"翠",nushu:["𛇂"]},
  {hanzi:"翰",nushu:["𛊧"]},
  {hanzi:"翻",nushu:["𛆠","𛆌"]},
  {hanzi:"老",nushu:["𛇽","𛇼"]},
  {hanzi:"考",nushu:["𛋰","𛆚","𛆄"]},
  {hanzi:"者",nushu:["𛈖","𛆆"]},
  {hanzi:"而",nushu:["𛇈"]},
  {hanzi:"耍",nushu:["𛉝"]},
  {hanzi:"耐",nushu:["𛉈"]},
  {hanzi:"耕",nushu:["𛈸","𛆃"]},
  {hanzi:"耗",nushu:["𛇮"]},
  {hanzi:"耳",nushu:["𛅺"]},
  {hanzi:"职",nushu:["𛊐"]},
  {hanzi:"联",nushu:["𛈏"]},
  {hanzi:"聘",nushu:["𛇲","𛆦"]},
  {hanzi:"聚",nushu:["𛇭"]},
  {hanzi:"聪",nushu:["𛉱"]},
  {hanzi:"肉",nushu:["𛈵"]},
  {hanzi:"肖",nushu:["𛈨"]},
  {hanzi:"肚",nushu:["𛋥"]},
  {hanzi:"肝",nushu:["𛇕"]},
  {hanzi:"肠",nushu:["𛊻"]},
  {hanzi:"股",nushu:["𛈅","𛇰"]},
  {hanzi:"肩",nushu:["𛉿"]},
  {hanzi:"肯",nushu:["𛊲","𛇉","𛆚"]},
  {hanzi:"肿",nushu:["𛆻"]},
  {hanzi:"胆",nushu:["𛉻"]},
  {hanzi:"背",nushu:["𛋲","𛇲"]},
  {hanzi:"胎",nushu:["𛉇"]},
  {hanzi:"胖",nushu:["𛋪","𛈺"]},
  {hanzi:"胜",nushu:["𛋐"]},
  {hanzi:"胞",nushu:["𛈲"]},
  {hanzi:"胡",nushu:["𛋘","𛇮"]},
  {hanzi:"胸",nushu:["𛉶"]},
  {hanzi:"能",nushu:["𛈷"]},
  {hanzi:"脂",nushu:["𛈤"]},
  {hanzi:"脑",nushu:["𛇊"]},
  {hanzi:"脚",nushu:["𛊐"]},
  {hanzi:"脱",nushu:["𛊱"]},
  {hanzi:"腊",nushu:["𛋗"]},
  {hanzi:"腐",nushu:["𛆖"]},
  {hanzi:"腔",nushu:["𛉱"]},
  {hanzi:"腮",nushu:["𛇏"]},
  {hanzi:"腰",nushu:["𛆱"]},
  {hanzi:"腹",nushu:["𛋷","𛊒","𛉖"]},
  {hanzi:"腾",nushu:["𛆒"]},
  {hanzi:"膝",nushu:["𛊶"]},
  {hanzi:"自",nushu:["𛈤"]},
  {hanzi:"臭",nushu:["𛈴"]},
  {hanzi:"至",nushu:["𛊝"]},
  {hanzi:"舂",nushu:["𛋥"]},
  {hanzi:"舅",nushu:["𛆝"]},
  {hanzi:"舍",nushu:["𛊍","𛉝"]},
  {hanzi:"舒",nushu:["𛈬"]},
  {hanzi:"舜",nushu:["𛉝"]},
  {hanzi:"舞",nushu:["𛅷"]},
  {hanzi:"般",nushu:["𛈺"]},
  {hanzi:"船",nushu:["𛈒"]},
  {hanzi:"良",nushu:["𛉴"]},
  {hanzi:"色",nushu:["𛇴"]},
  {hanzi:"艳",nushu:["𛈏"]},
  {hanzi:"节",nushu:["𛋓"]},
  {hanzi:"芙",nushu:["𛇮"]},
  {hanzi:"芦",nushu:["𛋗"]},
  {hanzi:"花",nushu:["𛈣"]},
  {hanzi:"芳",nushu:["𛆠"]},
  {hanzi:"芹",nushu:["𛊝"]},
  {hanzi:"芽",nushu:["𛊢"]},
  {hanzi:"苍",nushu:["𛉱"]},
  {hanzi:"苏",nushu:["𛊾"]},
  {hanzi:"苑",nushu:["𛈇"]},
  {hanzi:"苗",nushu:["𛋓","𛈳"]},
  {hanzi:"苟",nushu:["𛆄"]},
  {hanzi:"若",nushu:["𛇁"]},
  {hanzi:"苦",nushu:["𛇰"]},
  {hanzi:"英",nushu:["𛊫","𛊣"]},
  {hanzi:"范",nushu:["𛋶"]},
  {hanzi:"茄",nushu:["𛊻","𛆦"]},
  {hanzi:"茅",nushu:["𛋓","𛈳"]},
  {hanzi:"茫",nushu:["𛇓"]},
  {hanzi:"茶",nushu:["𛉗"]},
  {hanzi:"荆",nushu:["𛋭"]},
  {hanzi:"草",nushu:["𛉤"]},
  {hanzi:"荒",nushu:["𛊧"]},
  {hanzi:"荣",nushu:["𛆧"]},
  {hanzi:"荫",nushu:["𛆱"]},
  {hanzi:"药",nushu:["𛆱"]},
  {hanzi:"荷",nushu:["𛇮"]},
  {hanzi:"莫",nushu:["𛋖","𛉟"]},
  {hanzi:"莲",nushu:["𛉹"]},
  {hanzi:"莳",nushu:["𛅵"]},
  {hanzi:"菊",nushu:["𛊐"]},
  {hanzi:"菌",nushu:["𛊖"]},
  {hanzi:"菜",nushu:["𛈠"]},
  {hanzi:"萄",nushu:["𛊤"]},
  {hanzi:"萎",nushu:["𛊊"]},
  {hanzi:"落",nushu:["𛋝","𛈁"]},
  {hanzi:"著",nushu:["𛊖"]},
  {hanzi:"葛",nushu:["𛇵"]},
  {hanzi:"葬",nushu:["𛉱","𛆢"]},
  {hanzi:"葱",nushu:["𛋴"]},
  {hanzi:"蒋",nushu:["𛈼"]},
  {hanzi:"蒙",nushu:["𛋪","𛇓"]},
  {hanzi:"蒜",nushu:["𛆢"]},
  {hanzi:"蒲",nushu:["𛉖"]},
  {hanzi:"蓉",nushu:["𛈿"]},
  {hanzi:"蓑",nushu:["𛊾"]},
  {hanzi:"蓬",nushu:["𛊘"]},
  {hanzi:"蔗",nushu:["𛊶"]},
  {hanzi:"蔡",nushu:["𛈠"]},
  {hanzi:"蔫",nushu:["𛋍"]},
  {hanzi:"蔬",nushu:["𛊾"]},
  {hanzi:"蔸",nushu:["𛋧"]},
  {hanzi:"蕉",nushu:["𛊑"]},
  {hanzi:"薄",nushu:["𛉖"]},
  {hanzi:"薯",nushu:["𛋥"]},
  {hanzi:"藏",nushu:["𛈉"]},
  {hanzi:"虎",nushu:["𛇰"]},
  {hanzi:"虑",nushu:["𛇟","𛆍"]},
  {hanzi:"虚",nushu:["𛋐"]},
  {hanzi:"虽",nushu:["𛉅","𛆌"]},
  {hanzi:"蚁",nushu:["𛅺"]},
  {hanzi:"蚕",nushu:["𛋳","𛉑"]},
  {hanzi:"蛮",nushu:["𛇓"]},
  {hanzi:"蛰",nushu:["𛋔"]},
  {hanzi:"蜂",nushu:["𛅶"]},
  {hanzi:"蜜",nushu:["𛉟"]},
  {hanzi:"蝦",nushu:["𛈣","𛆐"]},
  {hanzi:"蝴",nushu:["𛇮"]},
  {hanzi:"螃",nushu:["𛋅"]},
  {hanzi:"融",nushu:["𛈿"]},
  {hanzi:"蠢",nushu:["𛈢"]},
  {hanzi:"血",nushu:["𛊗"]},
  {hanzi:"行",nushu:["𛊨","𛇐"]},
  {hanzi:"衔",nushu:["𛊨"]},
  {hanzi:"街",nushu:["𛉌","𛇧"]},
  {hanzi:"衙",nushu:["𛊢"]},
  {hanzi:"衡",nushu:["𛇐"]},
  {hanzi:"衣",nushu:["𛈡","𛆱"]},
  {hanzi:"补",nushu:["𛉖","𛆕"]},
  {hanzi:"表",nushu:["𛇅"]},
  {hanzi:"衫",nushu:["𛇏"]},
  {hanzi:"袋",nushu:["𛅻"]},
  {hanzi:"袍",nushu:["𛊘"]},
  {hanzi:"袖",nushu:["𛊶","𛉨"]},
  {hanzi:"袜",nushu:["𛋯"]},
  {hanzi:"被",nushu:["𛊰","𛉎","𛇣"]},
  {hanzi:"裁",nushu:["𛆏"]},
  {hanzi:"装",nushu:["𛈉"]},
  {hanzi:"裕",nushu:["𛆱"]},
  {hanzi:"裙",nushu:["𛊶","𛊵"]},
  {hanzi:"裤",nushu:["𛊶"]},
  {hanzi:"裳",nushu:["𛈾"]},
  {hanzi:"裹",nushu:["𛉄"]},
  {hanzi:"襟",nushu:["𛋔","𛆭"]},
  {hanzi:"西",nushu:["𛈨"]},
  {hanzi:"要",nushu:["𛇁","𛆴","𛆱","𛆯","𛅺"]},
  {hanzi:"见",nushu:["𛇝"]},
  {hanzi:"观",nushu:["𛇕"]},
  {hanzi:"规",nushu:["𛈘"]},
  {hanzi:"视",nushu:["𛆹"]},
  {hanzi:"觉",nushu:["𛉫"]},
  {hanzi:"角",nushu:["𛉫"]},
  {hanzi:"解",nushu:["𛊴"]},
  {hanzi:"言",nushu:["𛈔"]},
  {hanzi:"誓",nushu:["𛅵"]},
  {hanzi:"警",nushu:["𛇆"]},
  {hanzi:"譬",nushu:["𛈭"]},
  {hanzi:"计",nushu:["𛉓"]},
  {hanzi:"认",nushu:["𛅺"]},
  {hanzi:"讨",nushu:["𛇻"]},
  {hanzi:"让",nushu:["𛈍"]},
  {hanzi:"训",nushu:["𛊍"]},
  {hanzi:"议",nushu:["𛅺"]},
  {hanzi:"讯",nushu:["𛉡"]},
  {hanzi:"记",nushu:["𛉔","𛉓"]},
  {hanzi:"讲",nushu:["𛈯","𛇗"]},
  {hanzi:"许",nushu:["𛋱"]},
  {hanzi:"论",nushu:["𛉀"]},
  {hanzi:"设",nushu:["𛊗"]},
  {hanzi:"访",nushu:["𛋅"]},
  {hanzi:"证",nushu:["𛊝"]},
  {hanzi:"评",nushu:["𛇛"]},
  {hanzi:"识",nushu:["𛊗"]},
  {hanzi:"诉",nushu:["𛉅"]},
  {hanzi:"诊",nushu:["𛇆"]},
  {hanzi:"诗",nushu:["𛊸","𛆹"]},
  {hanzi:"诚",nushu:["𛈒"]},
  {hanzi:"话",nushu:["𛋶","𛈣"]},
  {hanzi:"诡",nushu:["𛈙"]},
  {hanzi:"该",nushu:["𛇧"]},
  {hanzi:"详",nushu:["𛈽"]},
  {hanzi:"语",nushu:["𛆱","𛅺"]},
  {hanzi:"误",nushu:["𛊃"]},
  {hanzi:"请",nushu:["𛉁"]},
  {hanzi:"诸",nushu:["𛊵"]},
  {hanzi:"读",nushu:["𛋥"]},
  {hanzi:"谁",nushu:["𛉅"]},
  {hanzi:"调",nushu:["𛉑","𛅹"]},
  {hanzi:"谅",nushu:["𛇖"]},
  {hanzi:"谈",nushu:["𛊤"]},
  {hanzi:"谊",nushu:["𛅺"]},
  {hanzi:"谋",nushu:["𛉟"]},
  {hanzi:"谓",nushu:["𛆨"]},
  {hanzi:"谢",nushu:["𛋮"]},
  {hanzi:"谷",nushu:["𛋸"]},
  {hanzi:"豆",nushu:["𛋛"]},
  {hanzi:"象",nushu:["𛊪"]},
  {hanzi:"豪",nushu:["𛇮"]},
  {hanzi:"豹",nushu:["𛆦"]},
  {hanzi:"贝",nushu:["𛊰"]},
  {hanzi:"贞",nushu:["𛆭"]},
  {hanzi:"负",nushu:["𛊓","𛆖"]},
  {hanzi:"财",nushu:["𛆏"]},
  {hanzi:"责",nushu:["𛋓"]},
  {hanzi:"贤",nushu:["𛊁"]},
  {hanzi:"败",nushu:["𛇣"]},
  {hanzi:"贪",nushu:["𛋃","𛆤"]},
  {hanzi:"贫",nushu:["𛊘"]},
  {hanzi:"贯",nushu:["𛆣"]},
  {hanzi:"贱",nushu:["𛋋"]},
  {hanzi:"贴",nushu:["𛉐"]},
  {hanzi:"贵",nushu:["𛋫"]},
  {hanzi:"费",nushu:["𛋻","𛇳","𛆌"]},
  {hanzi:"贺",nushu:["𛆖"]},
  {hanzi:"贼",nushu:["𛈤"]},
  {hanzi:"赋",nushu:["𛆖"]},
  {hanzi:"赌",nushu:["𛋦","𛊽"]},
  {hanzi:"赎",nushu:["𛋙","𛈬"]},
  {hanzi:"赏",nushu:["𛊤"]},
  {hanzi:"赐",nushu:["𛆹"]},
  {hanzi:"赔",nushu:["𛊘","𛇲"]},
  {hanzi:"赖",nushu:["𛉘"]},
  {hanzi:"赠",nushu:["𛉑"]},
  {hanzi:"赢",nushu:["𛋍","𛆧"]},
  {hanzi:"赦",nushu:["𛊍"]},
  {hanzi:"走",nushu:["𛈖"]},
  {hanzi:"赴",nushu:["𛈩"]},
  {hanzi:"赵",nushu:["𛉔","𛉓"]},
  {hanzi:"赶",nushu:["𛊦","𛇕"]},
  {hanzi:"起",nushu:["𛆻"]},
  {hanzi:"越",nushu:["𛋒"]},
  {hanzi:"趣",nushu:["𛇂"]},
  {hanzi:"足",nushu:["𛇭"]},
  {hanzi:"趾",nushu:["𛆑"]},
  {hanzi:"跛",nushu:["𛇣"]},
  {hanzi:"跟",nushu:["𛆃"]},
  {hanzi:"跨",nushu:["𛊶"]},
  {hanzi:"跪",nushu:["𛋫"]},
  {hanzi:"路",nushu:["𛋗"]},
  {hanzi:"跳",nushu:["𛉕"]},
  {hanzi:"跽",nushu:["𛉓"]},
  {hanzi:"踏",nushu:["𛋥"]},
  {hanzi:"踢",nushu:["𛉐"]},
  {hanzi:"踩",nushu:["𛋴","𛇦"]},
  {hanzi:"身",nushu:["𛈛"]},
  {hanzi:"车",nushu:["𛊌"]},
  {hanzi:"转",nushu:["𛋺","𛊶","𛇆"]},
  {hanzi:"轻",nushu:["𛊯"]},
  {hanzi:"载",nushu:["𛇥"]},
  {hanzi:"轿",nushu:["𛋔"]},
  {hanzi:"较",nushu:["𛆝"]},
  {hanzi:"辈",nushu:["𛊰"]},
  {hanzi:"辉",nushu:["𛆌"]},
  {hanzi:"输",nushu:["𛊼","𛈬"]},
  {hanzi:"辛",nushu:["𛊛","𛇹"]},
  {hanzi:"辞",nushu:["𛋳","𛋣"]},
  {hanzi:"辣",nushu:["𛉘","𛈞"]},
  {hanzi:"辫",nushu:["𛇙"]},
  {hanzi:"辰",nushu:["𛋙"]},
  {hanzi:"边",nushu:["𛇙"]},
  {hanzi:"达",nushu:["𛋥"]},
  {hanzi:"迁",nushu:["𛉱","𛆉"]},
  {hanzi:"过",nushu:["𛉘","𛇰","𛆅"]},
  {hanzi:"迎",nushu:["𛋍"]},
  {hanzi:"运",nushu:["𛇩"]},
  {hanzi:"还",nushu:["𛇐"]},
  {hanzi:"这",nushu:["𛋔"]},
  {hanzi:"进",nushu:["𛉑","𛈯"]},
  {hanzi:"远",nushu:["𛋟"]},
  {hanzi:"违",nushu:["𛊄"]},
  {hanzi:"连",nushu:["𛉹"]},
  {hanzi:"迟",nushu:["𛋣","𛊤"]},
  {hanzi:"迫",nushu:["𛈭","𛇫"]},
  {hanzi:"述",nushu:["𛉅"]},
  {hanzi:"迷",nushu:["𛇓"]},
  {hanzi:"退",nushu:["𛊇"]},
  {hanzi:"送",nushu:["𛉡","𛅿"]},
  {hanzi:"适",nushu:["𛇴"]},
  {hanzi:"逃",nushu:["𛊤"]},
  {hanzi:"逆",nushu:["𛈥"]},
  {hanzi:"逊",nushu:["𛊍"]},
  {hanzi:"逍",nushu:["𛈨"]},
  {hanzi:"透",nushu:["𛋃"]},
  {hanzi:"通",nushu:["𛉭","𛆤"]},
  {hanzi:"逝",nushu:["𛆓"]},
  {hanzi:"造",nushu:["𛊪"]},
  {hanzi:"逢",nushu:["𛋅","𛊘","𛆠"]},
  {hanzi:"逼",nushu:["𛉘"]},
  {hanzi:"遇",nushu:["𛇃"]},
  {hanzi:"道",nushu:["𛋛","𛇼"]},
  {hanzi:"遗",nushu:["𛆱","𛅺"]},
  {hanzi:"遭",nushu:["𛋳","𛊝"]},
  {hanzi:"遮",nushu:["𛊵"]},
  {hanzi:"遵",nushu:["𛊵"]},
  {hanzi:"避",nushu:["𛊰"]},
  {hanzi:"邀",nushu:["𛈕"]},
  {hanzi:"郁",nushu:["𛋍"]},
  {hanzi:"郎",nushu:["𛊥"]},
  {hanzi:"郡",nushu:["𛊶"]},
  {hanzi:"部",nushu:["𛉖"]},
  {hanzi:"都",nushu:["𛋗"]},
  {hanzi:"酉",nushu:["𛈶","𛈳"]},
  {hanzi:"酌",nushu:["𛊐"]},
  {hanzi:"配",nushu:["𛈭","𛇲"]},
  {hanzi:"酒",nushu:["𛊟","𛆆"]},
  {hanzi:"酬",nushu:["𛉬"]},
  {hanzi:"酸",nushu:["𛈊"]},
  {hanzi:"采",nushu:["𛉑","𛇦"]},
  {hanzi:"里",nushu:["𛉄"]},
  {hanzi:"重",nushu:["𛊻","𛊪","𛈯"]},
  {hanzi:"野",nushu:["𛇩"]},
  {hanzi:"量",nushu:["𛉴","𛇖"]},
  {hanzi:"金",nushu:["𛋔","𛆭"]},
  {hanzi:"针",nushu:["𛆭"]},
  {hanzi:"钉",nushu:["𛉼"]},
  {hanzi:"钗",nushu:["𛉉"]},
  {hanzi:"钢",nushu:["𛈌","𛇕"]},
  {hanzi:"钩",nushu:["𛋂"]},
  {hanzi:"钱",nushu:["𛋋"]},
  {hanzi:"铁",nushu:["𛉐"]},
  {hanzi:"铜",nushu:["𛆒"]},
  {hanzi:"铳",nushu:["𛋬"]},
  {hanzi:"银",nushu:["𛆰"]},
  {hanzi:"铺",nushu:["𛉖"]},
  {hanzi:"锁",nushu:["𛈂"]},
  {hanzi:"锄",nushu:["𛉗"]},
  {hanzi:"锅",nushu:["𛊿"]},
  {hanzi:"错",nushu:["𛋞","𛅲"]},
  {hanzi:"锡",nushu:["𛊈"]},
  {hanzi:"锦",nushu:["𛆻"]},
  {hanzi:"镇",nushu:["𛊝"]},
  {hanzi:"镜",nushu:["𛇆"]},
  {hanzi:"镶",nushu:["𛉵"]},
  {hanzi:"长",nushu:["𛋳","𛊻","𛊪","𛈽","𛈯","𛇗"]},
  {hanzi:"门",nushu:["𛋁","𛇷"]},
  {hanzi:"问",nushu:["𛋆","𛉟"]},
  {hanzi:"闰",nushu:["𛇩"]},
  {hanzi:"闲",nushu:["𛇐"]},
  {hanzi:"间",nushu:["𛈸","𛇕","𛆃"]},
  {hanzi:"闹",nushu:["𛈏"]},
  {hanzi:"闺",nushu:["𛋔","𛊵"]},
  {hanzi:"闻",nushu:["𛋁","𛇷","𛆂"]},
  {hanzi:"阁",nushu:["𛉦","𛇿"]},
  {hanzi:"阎",nushu:["𛋍"]},
  {hanzi:"队",nushu:["𛆬"]},
  {hanzi:"防",nushu:["𛋅"]},
  {hanzi:"阳",nushu:["𛈿"]},
  {hanzi:"阴",nushu:["𛆱"]},
  {hanzi:"阵",nushu:["𛋮"]},
  {hanzi:"阶",nushu:["𛉌","𛇧"]},
  {hanzi:"阻",nushu:["𛊽"]},
  {hanzi:"附",nushu:["𛊓","𛆖"]},
  {hanzi:"陈",nushu:["𛋳","𛊝"]},
  {hanzi:"降",nushu:["𛊪"]},
  {hanzi:"限",nushu:["𛇐"]},
  {hanzi:"院",nushu:["𛈇","𛆧"]},
  {hanzi:"除",nushu:["𛇭"]},
  {hanzi:"险",nushu:["𛉃"]},
  {hanzi:"陪",nushu:["𛊘","𛇲"]},
  {hanzi:"隆",nushu:["𛉴"]},
  {hanzi:"随",nushu:["𛉅"]},
  {hanzi:"隐",nushu:["𛋡"]},
  {hanzi:"隔",nushu:["𛈅"]},
  {hanzi:"难",nushu:["𛈷"]},
  {hanzi:"雄",nushu:["𛈾"]},
  {hanzi:"雕",nushu:["𛅾"]},
  {hanzi:"雨",nushu:["𛇯","𛅷"]},
  {hanzi:"雪",nushu:["𛊗"]},
  {hanzi:"零",nushu:["𛉼","𛉀"]},
  {hanzi:"雷",nushu:["𛊆","𛇟"]},
  {hanzi:"霜",nushu:["𛈊"]},
  {hanzi:"露",nushu:["𛋗"]},
  {hanzi:"霸",nushu:["𛇲"]},
  {hanzi:"青",nushu:["𛊭"]},
  {hanzi:"静",nushu:["𛉽"]},
  {hanzi:"非",nushu:["𛆌"]},
  {hanzi:"靠",nushu:["𛆣","𛆄"]},
  {hanzi:"面",nushu:["𛋉"]},
  {hanzi:"靴",nushu:["𛊍"]},
  {hanzi:"鞋",nushu:["𛇮"]},
  {hanzi:"鞍",nushu:["𛊃"]},
  {hanzi:"鞭",nushu:["𛇙"]},
  {hanzi:"韩",nushu:["𛊨"]},
  {hanzi:"韭",nushu:["𛆆"]},
  {hanzi:"音",nushu:["𛆱"]},
  {hanzi:"顺",nushu:["𛊍"]},
  {hanzi:"顾",nushu:["𛉘","𛆅"]},
  {hanzi:"顿",nushu:["𛆬"]},
  {hanzi:"颂",nushu:["𛊪"]},
  {hanzi:"领",nushu:["𛉼"]},
  {hanzi:"颈",nushu:["𛇆"]},
  {hanzi:"颜",nushu:["𛈕"]},
  {hanzi:"风",nushu:["𛋆","𛆠","𛆙"]},
  {hanzi:"飘",nushu:["𛅶"]},
  {hanzi:"飞",nushu:["𛆌"]},
  {hanzi:"食",nushu:["𛊼","𛆈"]},
  {hanzi:"餐",nushu:["𛉱"]},
  {hanzi:"饥",nushu:["𛋔"]},
  {hanzi:"饭",nushu:["𛈺","𛆌"]},
  {hanzi:"饮",nushu:["𛋡"]},
  {hanzi:"饱",nushu:["𛈲"]},
  {hanzi:"饿",nushu:["𛊃"]},
  {hanzi:"馆",nushu:["𛊦","𛇕"]},
  {hanzi:"馊",nushu:["𛇏"]},
  {hanzi:"首",nushu:["𛆞"]},
  {hanzi:"香",nushu:["𛉶"]},
  {hanzi:"马",nushu:["𛇀"]},
  {hanzi:"驴",nushu:["𛆽"]},
  {hanzi:"驼",nushu:["𛆒"]},
  {hanzi:"驾",nushu:["𛉋"]},
  {hanzi:"骂",nushu:["𛊾"]},
  {hanzi:"验",nushu:["𛈏"]},
  {hanzi:"骑",nushu:["𛊻"]},
  {hanzi:"骗",nushu:["𛅶"]},
  {hanzi:"骨",nushu:["𛆐"]},
  {hanzi:"高",nushu:["𛋂"]},
  {hanzi:"髻",nushu:["𛊝"]},
  {hanzi:"鬚",nushu:["𛊾"]},
  {hanzi:"鬼",nushu:["𛈙"]},
  {hanzi:"魂",nushu:["𛈮","𛆙"]},
  {hanzi:"魄",nushu:["𛋷"]},
  {hanzi:"鱼",nushu:["𛊢"]},
  {hanzi:"鲁",nushu:["𛋗"]},
  {hanzi:"鲜",nushu:["𛇚"]},
  {hanzi:"鲤",nushu:["𛉄"]},
  {hanzi:"鸟",nushu:["𛋒"]},
  {hanzi:"鸡",nushu:["𛋔"]},
  {hanzi:"鸣",nushu:["𛇾"]},
  {hanzi:"鸬",nushu:["𛋗"]},
  {hanzi:"鸭",nushu:["𛊮","𛆵"]},
  {hanzi:"鸯",nushu:["𛊫"]},
  {hanzi:"鸳",nushu:["𛊫"]},
  {hanzi:"鸽",nushu:["𛋸"]},
  {hanzi:"鸿",nushu:["𛉢"]},
  {hanzi:"鹅",nushu:["𛊢","𛇯"]},
  {hanzi:"麒",nushu:["𛋔","𛊻"]},
  {hanzi:"麟",nushu:["𛇇"]},
  {hanzi:"麦",nushu:["𛉟","𛇀"]},
  {hanzi:"麻",nushu:["𛇀"]},
  {hanzi:"黄",nushu:["𛊨"]},
  {hanzi:"黑",nushu:["𛋚"]},
  {hanzi:"默",nushu:["𛋍"]},
  {hanzi:"鼓",nushu:["𛇰"]},
  {hanzi:"鼠",nushu:["𛋱"]},
  {hanzi:"齐",nushu:["𛉒","𛉑"]},
  {hanzi:"齿",nushu:["𛇠"]},
  {hanzi:"龄",nushu:["𛉼","𛉀"]},
  {hanzi:"龙",nushu:["𛉴"]},
  {hanzi:"龟",nushu:["𛈘"]}
  ];
let NUSHU_MAP = {};

async function loadNushuData() {
  try {
    const res = await fetch('数据/nushu.json');
    if (!res.ok) throw new Error('Network error');
    const data = await res.json();
    NUSHU_DATA = data.map(item => ({
      hanzi: item.character,
      nushu: item.nushu
    }));
    NUSHU_DATA.forEach(item => {
      if (item.hanzi && item.nushu && item.nushu.length) {
        NUSHU_MAP[item.hanzi] = item.nushu;
      }
    });
  } catch (e) {
    console.error('Failed to load nushu.json:', e);
  }
}

// ===== Get all unique nushu characters =====
function getAllNushuChars() {
  const seen = new Map();
  NUSHU_DATA.forEach(item => {
    if (!seen.has(item.hanzi)) {
      seen.set(item.hanzi, item.nushu);
    }
  });
  return seen;
}

// ===== Convert text to nushu =====
function textToNushu(text) {
  const results = [];
  for (const char of text) {
    const entry = NUSHU_DATA.find(d => d.hanzi === char);
    if (entry) {
      results.push({ char, nushu: entry.nushu, found: true });
    } else {
      results.push({ char, nushu: [char], found: false });
    }
  }
  return results;
}

// ===== Render nushu output HTML =====
function renderNushuOutput(results) {
  return results.map(r => {
    return `<span class="char-item nushu-global" title="${r.nushu.join(' / ')}">${r.nushu[0]}</span>`;
  }).join('');
}

// ===== Get daily practice sentence =====
function getDailySentence() {
  const sentences = [
    { hanzi: "changqingnvshu，传承非遗文化", nushu: "𛆁𛉶𛊭𛆱𛊸𛆹" },
    { hanzi: "江永女书，世界唯一女性文字", nushu: "𛊨𛆧𛆁𛇉𛆚" },
    { hanzi: "一笔一画，书写女性的声音", nushu: "𛆞𛋓𛆞𛋓" },
    { hanzi: "女书之美，美在柔韧与力量", nushu: "𛆁𛇉𛆚𛋪" },
    { hanzi: "让我们一起守护女书文化", nushu: "𛊺𛆶𛊭𛆱" },
    { hanzi: "女书传情，文字载意", nushu: "𛆁𛇉𛆚𛋶" },
    { hanzi: "每一个女书字符，都是一段历史", nushu: "𛅳𛊝𛉠" },
    { hanzi: "传承千年的女性密码", nushu: "𛋔𛊝𛊻𛆥" },
  ];
  const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0)) / 86400000);
  return sentences[dayOfYear % sentences.length];
}

// ===== Submissions storage (localStorage) =====
function getSubmissions() {
  try {
    return JSON.parse(localStorage.getItem('nushu_submissions') || '[]');
  } catch {
    return [];
  }
}

function saveSubmission(data) {
  const subs = getSubmissions();
  subs.unshift({ ...data, id: Date.now() });
  // Keep last 100
  if (subs.length > 100) subs.length = 100;
  localStorage.setItem('nushu_submissions', JSON.stringify(subs));
}

// ===== Header scroll effect =====
function initHeader() {
  const header = document.querySelector('.site-header');
  if (!header) return;
  window.addEventListener('scroll', () => {
    header.classList.toggle('scrolled', window.scrollY > 20);
  });
}

// ===== Mobile menu =====
function initMobileMenu() {
  const toggle = document.querySelector('.menu-toggle');
  const nav = document.querySelector('.main-nav');
  if (!toggle || !nav) return;
  toggle.addEventListener('click', () => {
    nav.classList.toggle('open');
  });
};



function initHeroCard() {
  const mainChar = document.getElementById('heroMainChar');
  const subChars = document.getElementById('heroSubChars');
  const heroImg = document.getElementById('heroImg');
  if (!mainChar || !subChars) return;

  const pick = NUSHU_DATA[Math.floor(Math.random() * NUSHU_DATA.length)];
  const nushuChar = pick.nushu[0];
  const hanzi = pick.hanzi;

  mainChar.textContent = nushuChar;
  subChars.innerHTML = `<span class="chu">${hanzi}</span>`;

  if (heroImg) {
    heroImg.innerHTML = `<img src="图片/${nushuChar}.jpg" alt="${hanzi}" width="200" height="200" onerror="this.style.display='none'">`;
  }

  const float1 = document.getElementById('heroFloat1');
  const float2 = document.getElementById('heroFloat2');
  const float3 = document.getElementById('heroFloat3');
  if (float1) float1.textContent = nushuChar;
  if (float2) float2.textContent = nushuChar;
  if (float3) float3.textContent = nushuChar;

  const shuffleBtn = document.getElementById('heroShuffleBtn');
  if (shuffleBtn) {
    shuffleBtn.addEventListener('click', shuffleHeroCard);
  }
}

function shuffleHeroCard() {
  if (!NUSHU_DATA || NUSHU_DATA.length === 0) return;
  const pick = NUSHU_DATA[Math.floor(Math.random() * NUSHU_DATA.length)];
  const nushuChar = pick.nushu[0];
  const hanzi = pick.hanzi;

  const mainChar = document.getElementById('heroMainChar');
  const subChars = document.getElementById('heroSubChars');
  const heroImg = document.getElementById('heroImg');
  if (!mainChar) return;

  mainChar.classList.remove('shuffle-pop');
  void mainChar.offsetWidth;
  mainChar.classList.add('shuffle-pop');

  mainChar.textContent = nushuChar;
  if (subChars) subChars.innerHTML = `<span class="chu">${hanzi}</span>`;
  if (heroImg) {
    heroImg.innerHTML = `<img src="图片/${nushuChar}.jpg" alt="${hanzi}" width="200" height="200" onerror="this.style.display='none'">`;
  }

  const float1 = document.getElementById('heroFloat1');
  const float2 = document.getElementById('heroFloat2');
  const float3 = document.getElementById('heroFloat3');
  if (float1) float1.textContent = nushuChar;
  if (float2) float2.textContent = nushuChar;
  if (float3) float3.textContent = nushuChar;
}

// ===== Initialize common =====
document.addEventListener('DOMContentLoaded', async () => {
  await loadNushuData();
  initHeader();
  initMobileMenu();
  initLangSwitch();
  initHeroCard();
  setTimeout(startFloatingCards, 400);
});

// ===== Internationalization (i18n) =====
const I18N = {
  zh: {
    // Nav
    nav_home: '首页', nav_convert: '语言转换', nav_gallery: '字符展览',
    nav_courses: '传承人课程', nav_practice: '每日一练',
    // Hero
    hero_tag: '世界唯一女性文字',
    hero_title_1: '江永女书', hero_title_2: '千年的女性密语',
    hero_desc: '女书是湖南省江永县女性专属的表音文字体系，起源于明末清初，承载着旧时女性的生活、情感与智慧。每一个字符，都是一段不应被遗忘的历史。',
    hero_btn_convert: '开始转换', hero_btn_gallery: '字符展览',
    hero_card_label: '女书 · NUSHU',
    hero_card_meaning: '代表女性、女子',
    // Features
    feat_tag: '四大功能', feat_title: '探索女书文化之旅',
    feat_desc: '从汉字转换到字符展览，从传承人课程到每日一练，多维度体验女书的独特魅力。',
    feat_convert_title: '语言转换', feat_convert_desc: '输入汉字，即可看到对应的女书字符。收录3500+常用汉字与396个女书字符的对照。',
    feat_gallery_title: '字符展览', feat_gallery_desc: '396个女书字符如小牌子般陈列，点击翻转即可查看对应的汉字与释义。',
    feat_courses_title: '传承人课程', feat_courses_desc: '免费视频课程入门，扫码进入课程街观看完整付费课程，跟随传承人深入学习。',
    feat_practice_title: '每日一练', feat_practice_desc: '每天一句女书临摹练习，上传你的临摹作品，与大家共同传承女书文化。',
    // About
    about_tag: '关于女书', about_title: '什么是女书？',
    about_p1: '女书（Nüshu）是流传于湖南省永州市江永县的一种特殊文字，只在女性之间使用和传承，是迄今为止世界上发现的唯一一种完全由女性创造并使用的文字体系。',
    about_p2: '女书是一种标音文字，每个字符代表一个音节，与江永当地的土话相对应。女性用女书来写日记、通信、编唱等，记录她们的生活、情感和愿望。',
    stat_chars: '女书字符数', stat_hanzi: '收录汉字数', stat_years: '年历史传承', stat_unesco: '世界遗产认证',
    // Footer
    footer_about: '关于', footer_explore: '探索', footer_contact: '联系',
    footer_desc: '传承江永女书文化，让世界看见女性文字的独特魅力。常青女书致力于女书数字化保护与传播。',
    footer_copyright: '© 2026 常青女书 · NUSHU · 江永女书文化传播平台 · 仅供学习与文化传播使用',
    // Lang names
    lang_zh: '中文', lang_en: 'EN', lang_nushu: '𛆁𛈬',
    // Extra index keys
    feat_world_tag: '女书世界', feat_world_title: '女书 · 文字之美',
    feat_world_alt1: '女书海报1', feat_world_alt2: '女书海报2', feat_world_alt3: '女书海报3', feat_world_alt7: '女书海报7',
    about_img_alt: '女书文化',
    footer_about_link: '女书简介', footer_features_link: '功能介绍',
    footer_inheritor_link: '女书传承人', footer_coop_link: '合作咨询',
    aria_menu: '菜单',
    meta_desc: 'changqingnvshu — 江永女书文化传播平台，探索汉字与女书的转换，领略世界唯一女性文字的魅力。',
    brand_name: '常青女书',
    brand_title_home: '常青女书 · Changqing Nüshu',
    brand_title_convert: '语言转换 · 常青女书',
    brand_title_gallery: '字符展览 · 常青女书',
    brand_title_practice: '每日一练 · 常青女书',
    brand_title_courses: '传承人课程 · 常青女书',
    shuffle_label: '随机切换',
    aria_shuffle: '随机切换女书字符',
  },
  en: {
    nav_home: 'Home', nav_convert: 'Convert', nav_gallery: 'Gallery',
    nav_courses: 'Courses', nav_practice: 'Practice',
    hero_tag: "World's Only Women's Script",
    hero_title_1: 'Jiangyong Nüshu', hero_title_2: 'A Millennial Female Secret',
    hero_desc: "Nüshu is a phonetic script exclusive to women in Jiangyong County, Hunan Province, originating in the late Ming and early Qing dynasties. It carries the life, emotions and wisdom of women of that era. Every character is a piece of history that should not be forgotten.",
    hero_btn_convert: 'Start Converting', hero_btn_gallery: 'Character Gallery',
    hero_card_label: 'NUSHU · 𛆁𛈬',
    hero_card_meaning: 'Woman / Female',
    feat_tag: 'Four Features', feat_title: 'Explore Nüshu Culture',
    feat_desc: 'From Chinese-to-Nüshu conversion to character exhibitions, from inheritor courses to daily practice — experience the unique charm of Nüshu from multiple dimensions.',
    feat_convert_title: 'Language Conversion', feat_convert_desc: 'Enter Chinese characters to see corresponding Nüshu characters. Covers 3,500+ Chinese characters and 396 Nüshu characters.',
    feat_gallery_title: 'Character Exhibition', feat_gallery_desc: '396 Nüshu characters displayed like tiles — flip any card to see the corresponding Chinese character and meaning.',
    feat_courses_title: 'Inheritor Courses', feat_courses_desc: 'Free video courses to get started. Scan the QR code to access full paid courses taught by Nüshu inheritors.',
    feat_practice_title: 'Daily Practice', feat_practice_desc: 'Practice one Nüshu sentence every day, upload your calligraphy, and join the community in preserving this cultural heritage.',
    about_tag: 'About Nüshu', about_title: 'What is Nüshu?',
    about_p1: "Nüshu is a unique script passed down among women in Jiangyong County, Yongzhou, Hunan Province. It is the only script in the world known to have been created and used exclusively by women.",
    about_p2: "Nüshu is a phonetic script where each character represents a syllable, corresponding to the local Jiangyong dialect. Women used Nüshu to write diaries, letters, and songs, recording their lives, emotions and wishes.",
    stat_chars: 'Nüshu Characters', stat_hanzi: 'Chinese Mappings', stat_years: 'Years of Heritage', stat_unesco: 'UNESCO Listed',
    footer_about: 'About', footer_explore: 'Explore', footer_contact: 'Contact',
    footer_desc: 'Preserving and spreading Jiangyong Nüshu culture. Let the world see the unique charm of the women\'s script.',
    footer_copyright: '© 2026 changqingnvshu · NUSHU Cultural Heritage Platform · For educational and cultural use',
    lang_zh: '中文', lang_en: 'EN', lang_nushu: '𛆁𛈬',
    feat_world_tag: 'Nüshu World', feat_world_title: 'Nüshu · The Beauty of Script',
    feat_world_alt1: 'Nüshu Poster 1', feat_world_alt2: 'Nüshu Poster 2', feat_world_alt3: 'Nüshu Poster 3', feat_world_alt7: 'Nüshu Poster 7',
    about_img_alt: 'Nüshu Culture',
    footer_about_link: 'About Nüshu', footer_features_link: 'Features',
    footer_inheritor_link: 'Nüshu Inheritor', footer_coop_link: 'Cooperation',
    aria_menu: 'Menu',
    meta_desc: 'changqingnvshu — Jiangyong Nüshu cultural heritage platform. Explore Chinese-to-Nüshu conversion and experience the world\'s only women\'s script.',
    brand_name: 'changqingnvshu',
    brand_title_home: 'changqingnvshu',
    brand_title_convert: 'Language Conversion · changqingnvshu',
    brand_title_gallery: 'Character Exhibition · changqingnvshu',
    brand_title_practice: 'Daily Practice · changqingnvshu',
    brand_title_courses: 'Courses · changqingnvshu',
    shuffle_label: 'Random',
    aria_shuffle: 'Random shuffle Nüshu character',
  },
  nushu: {

    nav_home: '𛆞𛇩', nav_convert: '𛅺𛈔𛋺𛊧', nav_gallery: '𛈤𛆖𛊀𛋂',
    nav_courses: '𛈆𛋙𛅳𛋰𛈆', nav_practice: '𛉟𛇈𛅰𛈏',

    hero_tag: '𛆓𛆄𛊄𛅰𛆁𛉾𛆂𛈤',
    hero_title_1: '𛈌𛈍𛆁𛈬', hero_title_2: '𛆉𛆥𛉘𛆁𛉾𛇓𛅺',
    hero_desc: '𛆁𛈬𛆹𛋘𛉺𛊜𛈌𛈍𛋟𛆁𛉾𛈌𛊼𛉘𛇅𛆱𛆂𛈤𛋒𛆱，𛆻𛆧𛆱𛇾𛋍𛊭𛊾，𛋙𛇥𛊖𛆝𛆸𛆁𛉾𛉘𛇏𛋶、𛊭𛇕𛆱𛊝𛆌。𛉟𛅰𛆅𛈤𛆖，𛋗𛆹𛅰𛋇𛆳𛆱𛇣𛅺𛆡𛉘𛉄𛆹。',
    hero_btn_convert: '𛇶𛇴𛋺𛊧', hero_btn_gal𛆿ery: '𛈤𛆖𛊀𛋂',hero_btn_gallery: '𛈤𛆖𛊀𛋂',
    hero_card_label: '𛆁𛈬 · NUSHU',
    hero_card_meaning: '𛅻𛇅𛆁𛉾、𛆁𛆑',

    feat_tag: '𛈗𛅻𛆃𛈷', feat_title: '𛋃𛈂𛆁𛈬𛆂𛅽𛆷𛆽',
    feat_desc: '𛈽𛊧𛈤𛋺𛊧𛆛𛈤𛆖𛊀𛋂，𛈽𛈆𛋙𛅳𛋰𛈆𛆛𛉟𛇈𛅰𛈏，𛈁𛊄𛋥𛋒𛈏𛆁𛈬𛉘𛋥𛆶𛋪𛉄。',
    feat_convert_title: '𛅺𛈔𛋺𛊧', feat_convert_desc: '𛈬𛅱𛊧𛈤，𛋔𛆄𛆣𛆛𛆬𛆱𛉘𛆁𛈬𛈤𛆖。𛈀𛋗350𛆿+𛈾𛈍𛊧𛈤𛆱396𛆅𛆁𛈬𛈤𛆖𛉘𛆬𛉔。',
    feat_gallery_title: '𛈤𛆖𛊀𛋂', feat_gallery_desc: '396𛆅𛆁𛈬𛈤𛆖𛇄𛅿𛇢𛆑𛈺𛊝𛆍，𛉸𛊐𛆠𛋺𛋔𛆄𛉗𛆣𛆬𛆱𛉘𛊧𛈤𛆱𛆈𛅺。',
    feat_courses_title: '𛈆𛋙𛅳𛋰𛈆', feat_courses_desc: '𛋉𛋻𛆹𛊘𛋰𛈆𛅱𛋁，𛈗𛇀𛈯𛅱𛋰𛈆𛉌𛇕𛆣𛆧𛇆𛆖𛋻𛋰𛈆，𛆃𛉅𛈆𛋙𛅳𛈛𛅱𛉬𛆓。',
    feat_practice_title: '𛉟𛇈𛅰𛈏', feat_practice_desc: '𛉟𛆤𛅰𛆘𛆁𛈬𛇇𛋍𛈏𛆓，𛆈𛈆𛈪𛉘𛇇𛋍𛇍𛉞，𛆱𛅻𛉊𛈌𛊤𛈆𛋙𛆁𛈬𛆂𛅽。',
    about_img_alt: '𛆁𛈬𛆂𛅽',
    feat_world_tag: '𛆁𛈬𛆓𛆄', feat_world_title: '𛆁𛈬 · 𛆂𛈤𛆷𛋪',
    feat_world_alt1: '𛆁𛈬𛉝𛇣1', feat_world_alt2: '𛆁𛈬𛉝𛇣2', feat_world_alt3: '𛆁𛈬𛉝𛇣3', feat_world_alt7: '𛆁𛈬𛉝𛇣7',
    about_img_alt: '𛆁𛈬𛆂𛅽',
    footer_about_link: '𛆁𛈬𛆃𛆄', footer_features_link: '𛆃𛈷𛆄𛋙',
    footer_inheritor_link: '𛆁𛈬𛈆𛋙𛅳', footer_coop_link: '𛈩𛇍𛈤𛊍',
    aria_menu: '𛈠𛆍',
    meta_desc: '𛈾𛊭𛆁𛈬 — 𛈌𛈍𛆁𛈬𛆂𛅽𛈆𛇣𛇛𛅻，𛋃𛈂𛊧𛈤𛆱𛆁𛈬𛉘𛋺𛊧，𛉼𛆜𛆓𛆄𛊄𛅰𛆁𛉾𛆂𛈤𛉘𛋪𛉄。',
    brand_name: '𛈾𛊭𛆁𛈬',
    brand_title_home: '𛈾𛊭𛆁𛈬 · Changqing Nüshu',
    brand_title_convert: '𛅺𛈔𛋺𛊧 · 𛈾𛊭𛆁𛈬',
    brand_title_gal𛆿ery: '𛈤𛆖𛊀𛋂 · 𛈾𛊭𛆁𛈬',
    brand_title_practice: '𛉟𛇈𛅰𛈏 · 𛈾𛊭𛆁𛈬',
    brand_title_courses: '𛈆𛋙𛅳𛋰𛈆 · 𛈾𛊭𛆁𛈬',
    footer_about: '𛇕𛆱', footer_explore: '𛋃𛈂', footer_contact: '𛈏𛆱',
    footer_desc: '𛈆𛋙𛈌𛈍𛆁𛈬𛆂𛅽，𛈍𛆓𛆄𛆣𛇝𛆁𛉾𛆂𛈤𛉘𛋥𛆶𛋪𛉄。𛈾𛊭𛆁𛈬𛆑𛉄𛆱𛆁𛈬𛉅𛈤𛅽𛉎𛇮𛆱𛈆𛇣。',
    footer_copyright: '© 2026 𛈾𛊭𛆁𛈬 · NUSHU · 𛈌𛈍𛆁𛈬𛆂𛅽𛈆𛇣𛇛𛅻 · 𛆻𛈌𛉬𛆓𛆱𛆂𛅽𛈆𛇣𛇴𛈍',
    about_tag: '𛇕𛆱𛆁𛈬', about_title: '𛈛𛇀𛆹𛆁𛈬？',
    about_p1: '𛆁𛈬（Nüshu）𛆹𛇋𛈆𛆱𛋘𛉺𛊜𛈍𛆝𛆹𛈌𛈍𛋟𛉘𛅰𛊪𛆶𛋙𛆂𛈤，𛆑𛇥𛆁𛉾𛆷𛈸𛇴𛈍𛇮𛈆𛋙，𛆹𛉑𛆭𛆨𛆑𛆓𛆄𛆈𛆐𛉃𛉘𛊄𛅰𛆿𛊪𛆧𛈆𛊢𛆁𛉾𛉱𛊪𛆦𛇴𛈍𛉘𛆂𛈤𛋒𛆱。',
    about_p2: '𛆁𛈬𛆹𛅰𛊪𛅶𛆱𛆂𛈤，𛉟𛆅𛈤𛆖𛅻𛇅𛅰𛆅𛆱𛋓，𛆱𛈌𛈍𛉰𛊤𛉘𛆀𛈣𛊩𛆬𛆱。𛆁𛉾𛈍𛆁𛈬𛇤𛇠𛇈𛉓、𛆤𛉡、𛇙𛋬𛉠，𛉓𛋗𛋥𛇷𛉘𛇏𛋶、𛊭𛇕𛇮𛋟𛈈。',
    stat_chars: '𛆁𛈬𛈤𛆖𛉅', stat_hanzi: '𛈀𛋗𛊧𛈤𛉅', stat_years: '𛆥𛉄𛆹𛈆𛋙', stat_unesco: '𛆓𛆄𛅺𛊜𛅺𛊝',
  }
};

let currentLang = localStorage.getItem('nushu_lang') || 'zh';

function setLanguage(lang) {
  currentLang = lang;
  localStorage.setItem('nushu_lang', lang);

  // Update all i18n elements
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (I18N[lang] && I18N[lang][key]) {
      el.textContent = I18N[lang][key];
    }
  });

  // Update i18n-placeholder elements
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (I18N[lang] && I18N[lang][key]) {
      el.placeholder = I18N[lang][key];
    }
  });

  // Update i18n-alt elements
  document.querySelectorAll('[data-i18n-alt]').forEach(el => {
    const key = el.getAttribute('data-i18n-alt');
    if (I18N[lang] && I18N[lang][key]) {
      el.alt = I18N[lang][key];
    }
  });

  // Update i18n-aria elements (aria-label)
  document.querySelectorAll('[data-i18n-aria]').forEach(el => {
    const key = el.getAttribute('data-i18n-aria');
    if (I18N[lang] && I18N[lang][key]) {
      el.setAttribute('aria-label', I18N[lang][key]);
    }
  });

  // Update page title
  const pageTitleKey = document.querySelector('title[data-i18n]')?.getAttribute('data-i18n');
  if (pageTitleKey && I18N[lang]?.[pageTitleKey]) {
    document.title = I18N[lang][pageTitleKey];
  }

  // Update meta description
  document.querySelectorAll('meta[data-i18n-content]').forEach(el => {
    const key = el.getAttribute('data-i18n-content');
    if (I18N[lang] && I18N[lang][key]) {
      el.content = I18N[lang][key];
    }
  });

  // Update active lang button
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });

  // Re-render page-specific content
  if (typeof onLangChange === 'function') onLangChange(lang);
}

function initLangSwitch() {
  // Inject switcher into all headers
  document.querySelectorAll('.header-inner').forEach(header => {
    // Remove existing if any
    const existing = header.querySelector('.header-lang');
    if (existing) return;

    const langArea = document.createElement('div');
    langArea.className = 'header-lang';
    langArea.innerHTML = `
      <div class="lang-switcher">
        <button class="lang-btn ${currentLang === 'zh' ? 'active' : ''}" data-lang="zh">中文</button>
        <button class="lang-btn ${currentLang === 'en' ? 'active' : ''}" data-lang="en">EN</button>
        <button class="lang-btn ${currentLang === 'nushu' ? 'active' : ''}" data-lang="nushu">𛆁𛈬</button>
      </div>
    `;
    header.appendChild(langArea);

    langArea.querySelectorAll('.lang-btn').forEach(btn => {
      btn.addEventListener('click', () => setLanguage(btn.dataset.lang));
    });
  });

  // Apply saved language
  setLanguage(currentLang);
}

function getRandomNushu() {
  const entry = NUSHU_DATA[Math.floor(Math.random() * NUSHU_DATA.length)];
  const nushuChar = entry.nushu[Math.floor(Math.random() * entry.nushu.length)];
  return nushuChar;
}

function spawnFloatingCard() {
  const container = document.getElementById('floatingCards');
  if (!container) return;

  const existing = container.querySelectorAll('.floating-card:not(.fc-exit)');
  if (existing.length >= 3) return;

  const count = Math.floor(Math.random() * 3) + 1;
  const corners = [
    { x: 8,  y: 10 }, { x: 50, y: 10 }, { x: 85, y: 10 },
    { x: 8,  y: 40 }, { x: 50, y: 40 }, { x: 85, y: 40 },
    { x: 8,  y: 70 }, { x: 50, y: 70 }, { x: 85, y: 70 },
  ];

  const used = [];
  for (let i = 0; i < count; i++) {
    const avail = corners.filter((_, idx) => !used.includes(idx));
    if (!avail.length) break;
    const pick = avail[Math.floor(Math.random() * avail.length)];
    const cornerIdx = corners.indexOf(pick);
    used.push(cornerIdx);

    const nushuChar = getRandomNushu();
    const card = document.createElement('div');
    const fromLeft = Math.random() < 0.5;
    card.className = 'floating-card ' + (fromLeft ? 'fc-enter-left' : 'fc-enter-right');
    card.textContent = nushuChar;
    card.style.left = pick.x + '%';
    card.style.top = pick.y + '%';
    card.style.transform = 'translateY(-50%)';
    container.appendChild(card);
    card.addEventListener('animationend', () => card.remove());
  }
}

function startFloatingCards() {
  if (window.innerWidth < 768) return;
  spawnFloatingCard();
  setInterval(spawnFloatingCard, 2200);
}

// ===== Loading Screen =====
function hideLoadingScreen() {
  const screen = document.getElementById('loadingScreen');
  if (screen) screen.classList.add('hidden');
}

window.addEventListener('load', () => {
  setTimeout(hideLoadingScreen, 1500);
});
